// flow-typed signature: e9b77af1d784a32c224227be18be33ef
// flow-typed version: <<STUB>>/changelog_v^1.3.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'changelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'changelog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'changelog/bin/changelog' {
  declare module.exports: any;
}

declare module 'changelog/Gruntfile' {
  declare module.exports: any;
}

declare module 'changelog/lib/changelog' {
  declare module.exports: any;
}

declare module 'changelog/lib/cli' {
  declare module.exports: any;
}

declare module 'changelog/lib/datasrc/github' {
  declare module.exports: any;
}

declare module 'changelog/lib/datasrc/npm' {
  declare module.exports: any;
}

declare module 'changelog/lib/log' {
  declare module.exports: any;
}

declare module 'changelog/lib/output/markdown' {
  declare module.exports: any;
}

declare module 'changelog/lib/output/terminal' {
  declare module.exports: any;
}

declare module 'changelog/lib/util/bullet' {
  declare module.exports: any;
}

declare module 'changelog/lib/util/userAgent' {
  declare module.exports: any;
}

declare module 'changelog/lib/util/versionFilter' {
  declare module.exports: any;
}

declare module 'changelog/test/changelog.test' {
  declare module.exports: any;
}

declare module 'changelog/test/github.test' {
  declare module.exports: any;
}

declare module 'changelog/test/npm.test' {
  declare module.exports: any;
}

declare module 'changelog/test/versionFilter.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'changelog/bin/changelog.js' {
  declare module.exports: $Exports<'changelog/bin/changelog'>;
}
declare module 'changelog/Gruntfile.js' {
  declare module.exports: $Exports<'changelog/Gruntfile'>;
}
declare module 'changelog/lib/changelog.js' {
  declare module.exports: $Exports<'changelog/lib/changelog'>;
}
declare module 'changelog/lib/cli.js' {
  declare module.exports: $Exports<'changelog/lib/cli'>;
}
declare module 'changelog/lib/datasrc/github.js' {
  declare module.exports: $Exports<'changelog/lib/datasrc/github'>;
}
declare module 'changelog/lib/datasrc/npm.js' {
  declare module.exports: $Exports<'changelog/lib/datasrc/npm'>;
}
declare module 'changelog/lib/log.js' {
  declare module.exports: $Exports<'changelog/lib/log'>;
}
declare module 'changelog/lib/output/markdown.js' {
  declare module.exports: $Exports<'changelog/lib/output/markdown'>;
}
declare module 'changelog/lib/output/terminal.js' {
  declare module.exports: $Exports<'changelog/lib/output/terminal'>;
}
declare module 'changelog/lib/util/bullet.js' {
  declare module.exports: $Exports<'changelog/lib/util/bullet'>;
}
declare module 'changelog/lib/util/userAgent.js' {
  declare module.exports: $Exports<'changelog/lib/util/userAgent'>;
}
declare module 'changelog/lib/util/versionFilter.js' {
  declare module.exports: $Exports<'changelog/lib/util/versionFilter'>;
}
declare module 'changelog/test/changelog.test.js' {
  declare module.exports: $Exports<'changelog/test/changelog.test'>;
}
declare module 'changelog/test/github.test.js' {
  declare module.exports: $Exports<'changelog/test/github.test'>;
}
declare module 'changelog/test/npm.test.js' {
  declare module.exports: $Exports<'changelog/test/npm.test'>;
}
declare module 'changelog/test/versionFilter.test.js' {
  declare module.exports: $Exports<'changelog/test/versionFilter.test'>;
}
