// flow-typed signature: 0dbc9fb0a221123bd89ba5d27807bcdb
// flow-typed version: <<STUB>>/co-wait_v^0.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'co-wait'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'co-wait' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'co-wait/example' {
  declare module.exports: any;
}

declare module 'co-wait/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'co-wait/example.js' {
  declare module.exports: $Exports<'co-wait/example'>;
}
declare module 'co-wait/index' {
  declare module.exports: $Exports<'co-wait'>;
}
declare module 'co-wait/index.js' {
  declare module.exports: $Exports<'co-wait'>;
}
declare module 'co-wait/test.js' {
  declare module.exports: $Exports<'co-wait/test'>;
}
