// flow-typed signature: 0ed85b0d5f4d574dda27f44d14a2d7d2
// flow-typed version: <<STUB>>/lodash.frompairs_v^4.0.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.frompairs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.frompairs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.frompairs/index' {
  declare module.exports: $Exports<'lodash.frompairs'>;
}
declare module 'lodash.frompairs/index.js' {
  declare module.exports: $Exports<'lodash.frompairs'>;
}
