// flow-typed signature: 37b8b66fad1924f34634029f10cf0e5b
// flow-typed version: <<STUB>>/lodash.values_v^4.3.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.values'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.values' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.values/index' {
  declare module.exports: $Exports<'lodash.values'>;
}
declare module 'lodash.values/index.js' {
  declare module.exports: $Exports<'lodash.values'>;
}
