// flow-typed signature: 316354cecb2ecb3c676721b519c75ef8
// flow-typed version: <<STUB>>/lodash.sumby_v^4.6.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.sumby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.sumby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.sumby/index' {
  declare module.exports: $Exports<'lodash.sumby'>;
}
declare module 'lodash.sumby/index.js' {
  declare module.exports: $Exports<'lodash.sumby'>;
}
