// flow-typed signature: c649f8684fd478ef442eeb43ebd94438
// flow-typed version: <<STUB>>/lodash.findindex_v^4.6.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.findindex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.findindex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.findindex/index' {
  declare module.exports: $Exports<'lodash.findindex'>;
}
declare module 'lodash.findindex/index.js' {
  declare module.exports: $Exports<'lodash.findindex'>;
}
