// flow-typed signature: 81b8ab399a751724fdf59f1c175616c7
// flow-typed version: <<STUB>>/lodash.mapkeys_v^4.6.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.mapkeys'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.mapkeys' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.mapkeys/index' {
  declare module.exports: $Exports<'lodash.mapkeys'>;
}
declare module 'lodash.mapkeys/index.js' {
  declare module.exports: $Exports<'lodash.mapkeys'>;
}
