// flow-typed signature: 56376f64b96ad936036be59d4f887cee
// flow-typed version: <<STUB>>/lodash.topairs_v^4.3.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.topairs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.topairs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.topairs/index' {
  declare module.exports: $Exports<'lodash.topairs'>;
}
declare module 'lodash.topairs/index.js' {
  declare module.exports: $Exports<'lodash.topairs'>;
}
