// flow-typed signature: fd01654064dc1d0dc0e845c746c16261
// flow-typed version: <<STUB>>/lodash.pad_v^4.5.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.pad'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.pad' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.pad/index' {
  declare module.exports: $Exports<'lodash.pad'>;
}
declare module 'lodash.pad/index.js' {
  declare module.exports: $Exports<'lodash.pad'>;
}
