// flow-typed signature: af373dbbac6c01470375aff10615734f
// flow-typed version: <<STUB>>/lodash.mean_v^4.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.mean'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.mean' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.mean/index' {
  declare module.exports: $Exports<'lodash.mean'>;
}
declare module 'lodash.mean/index.js' {
  declare module.exports: $Exports<'lodash.mean'>;
}
