// flow-typed signature: 88522ac0850506bfc09e3998ffc5ba39
// flow-typed version: <<STUB>>/lodash.zip_v^4.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.zip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.zip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.zip/index' {
  declare module.exports: $Exports<'lodash.zip'>;
}
declare module 'lodash.zip/index.js' {
  declare module.exports: $Exports<'lodash.zip'>;
}
