// flow-typed signature: fce2e18a590b83e4ee9e54a6726bfd63
// flow-typed version: <<STUB>>/lodash.reduce_v^4.6.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.reduce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.reduce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.reduce/index' {
  declare module.exports: $Exports<'lodash.reduce'>;
}
declare module 'lodash.reduce/index.js' {
  declare module.exports: $Exports<'lodash.reduce'>;
}
