// flow-typed signature: 2270f451e5c3840cc8a9cb96db4306af
// flow-typed version: <<STUB>>/lodash.truncate_v^4.4.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.truncate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.truncate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.truncate/index' {
  declare module.exports: $Exports<'lodash.truncate'>;
}
declare module 'lodash.truncate/index.js' {
  declare module.exports: $Exports<'lodash.truncate'>;
}
