// flow-typed signature: 1a892a82f77a47c3795bf3f0caf05da5
// flow-typed version: <<STUB>>/lodash.countby_v^4.6.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.countby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.countby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.countby/index' {
  declare module.exports: $Exports<'lodash.countby'>;
}
declare module 'lodash.countby/index.js' {
  declare module.exports: $Exports<'lodash.countby'>;
}
