// flow-typed signature: 217ccd65e1f9f9b80622dd805abeed18
// flow-typed version: <<STUB>>/shell-escape_v^0.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shell-escape'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shell-escape' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shell-escape/shell-escape' {
  declare module.exports: any;
}

declare module 'shell-escape/test/advanced' {
  declare module.exports: any;
}

declare module 'shell-escape/test/more' {
  declare module.exports: any;
}

declare module 'shell-escape/test/simple' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shell-escape/shell-escape.js' {
  declare module.exports: $Exports<'shell-escape/shell-escape'>;
}
declare module 'shell-escape/test/advanced.js' {
  declare module.exports: $Exports<'shell-escape/test/advanced'>;
}
declare module 'shell-escape/test/more.js' {
  declare module.exports: $Exports<'shell-escape/test/more'>;
}
declare module 'shell-escape/test/simple.js' {
  declare module.exports: $Exports<'shell-escape/test/simple'>;
}
