// flow-typed signature: 49b8ccbe1fc621493ca49442515b0d2d
// flow-typed version: <<STUB>>/sparkline_v^0.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sparkline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sparkline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sparkline/Gruntfile' {
  declare module.exports: any;
}

declare module 'sparkline/lib/sparkline' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sparkline/Gruntfile.js' {
  declare module.exports: $Exports<'sparkline/Gruntfile'>;
}
declare module 'sparkline/lib/sparkline.js' {
  declare module.exports: $Exports<'sparkline/lib/sparkline'>;
}
