// flow-typed signature: a8351c733971c79eaa88c06371b13b17
// flow-typed version: <<STUB>>/strftime_v^0.10.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'strftime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'strftime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'strftime/millis' {
  declare module.exports: any;
}

declare module 'strftime/strftime-min' {
  declare module.exports: any;
}

declare module 'strftime/strftime' {
  declare module.exports: any;
}

declare module 'strftime/test-dst' {
  declare module.exports: any;
}

declare module 'strftime/test-week' {
  declare module.exports: any;
}

declare module 'strftime/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'strftime/millis.js' {
  declare module.exports: $Exports<'strftime/millis'>;
}
declare module 'strftime/strftime-min.js' {
  declare module.exports: $Exports<'strftime/strftime-min'>;
}
declare module 'strftime/strftime.js' {
  declare module.exports: $Exports<'strftime/strftime'>;
}
declare module 'strftime/test-dst.js' {
  declare module.exports: $Exports<'strftime/test-dst'>;
}
declare module 'strftime/test-week.js' {
  declare module.exports: $Exports<'strftime/test-week'>;
}
declare module 'strftime/test.js' {
  declare module.exports: $Exports<'strftime/test'>;
}
