// flow-typed signature: bfbbd701f7750131729125981d8bfed7
// flow-typed version: <<STUB>>/term-img_v^1.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'term-img'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'term-img' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'term-img/index' {
  declare module.exports: $Exports<'term-img'>;
}
declare module 'term-img/index.js' {
  declare module.exports: $Exports<'term-img'>;
}
