// flow-typed signature: 740d4af404cfbe4ba864798db69b2831
// flow-typed version: <<STUB>>/co_v4.6.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'co'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'co' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'co/index' {
  declare module.exports: $Exports<'co'>;
}
declare module 'co/index.js' {
  declare module.exports: $Exports<'co'>;
}
