// flow-typed signature: 67ce400adf33ca16ca6d51628b292b75
// flow-typed version: <<STUB>>/heroku-cli-util_v6.1.17/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-cli-util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-cli-util' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-cli-util/lib/action' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/auth' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/color' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/command' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/console' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/date' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/errors' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/exit' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/got' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/linewrap' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/mutex' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/open' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/preauth' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/process' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/prompt' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/spinner' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/styled' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/table' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/util' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/vars' {
  declare module.exports: any;
}

declare module 'heroku-cli-util/lib/yubikey' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-cli-util/index' {
  declare module.exports: $Exports<'heroku-cli-util'>;
}
declare module 'heroku-cli-util/index.js' {
  declare module.exports: $Exports<'heroku-cli-util'>;
}
declare module 'heroku-cli-util/lib/action.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/action'>;
}
declare module 'heroku-cli-util/lib/auth.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/auth'>;
}
declare module 'heroku-cli-util/lib/color.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/color'>;
}
declare module 'heroku-cli-util/lib/command.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/command'>;
}
declare module 'heroku-cli-util/lib/console.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/console'>;
}
declare module 'heroku-cli-util/lib/date.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/date'>;
}
declare module 'heroku-cli-util/lib/errors.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/errors'>;
}
declare module 'heroku-cli-util/lib/exit.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/exit'>;
}
declare module 'heroku-cli-util/lib/got.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/got'>;
}
declare module 'heroku-cli-util/lib/linewrap.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/linewrap'>;
}
declare module 'heroku-cli-util/lib/mutex.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/mutex'>;
}
declare module 'heroku-cli-util/lib/open.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/open'>;
}
declare module 'heroku-cli-util/lib/preauth.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/preauth'>;
}
declare module 'heroku-cli-util/lib/process.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/process'>;
}
declare module 'heroku-cli-util/lib/prompt.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/prompt'>;
}
declare module 'heroku-cli-util/lib/spinner.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/spinner'>;
}
declare module 'heroku-cli-util/lib/styled.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/styled'>;
}
declare module 'heroku-cli-util/lib/table.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/table'>;
}
declare module 'heroku-cli-util/lib/util.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/util'>;
}
declare module 'heroku-cli-util/lib/vars.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/vars'>;
}
declare module 'heroku-cli-util/lib/yubikey.js' {
  declare module.exports: $Exports<'heroku-cli-util/lib/yubikey'>;
}
