// flow-typed signature: 024b6549fd33607daba247d456086a50
// flow-typed version: <<STUB>>/lodash.maxby_v4.6.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.maxby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.maxby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.maxby/index' {
  declare module.exports: $Exports<'lodash.maxby'>;
}
declare module 'lodash.maxby/index.js' {
  declare module.exports: $Exports<'lodash.maxby'>;
}
