// flow-typed signature: 6c54c04e83d9bc270ca86f97e353e0a8
// flow-typed version: <<STUB>>/sprintf-js_v1.1.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sprintf-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sprintf-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sprintf-js/benchmark/benchmark' {
  declare module.exports: any;
}

declare module 'sprintf-js/dist/angular-sprintf.min' {
  declare module.exports: any;
}

declare module 'sprintf-js/dist/sprintf.min' {
  declare module.exports: any;
}

declare module 'sprintf-js/gulpfile' {
  declare module.exports: any;
}

declare module 'sprintf-js/src/angular-sprintf' {
  declare module.exports: any;
}

declare module 'sprintf-js/src/sprintf' {
  declare module.exports: any;
}

declare module 'sprintf-js/test/test_validation' {
  declare module.exports: any;
}

declare module 'sprintf-js/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sprintf-js/benchmark/benchmark.js' {
  declare module.exports: $Exports<'sprintf-js/benchmark/benchmark'>;
}
declare module 'sprintf-js/dist/angular-sprintf.min.js' {
  declare module.exports: $Exports<'sprintf-js/dist/angular-sprintf.min'>;
}
declare module 'sprintf-js/dist/sprintf.min.js' {
  declare module.exports: $Exports<'sprintf-js/dist/sprintf.min'>;
}
declare module 'sprintf-js/gulpfile.js' {
  declare module.exports: $Exports<'sprintf-js/gulpfile'>;
}
declare module 'sprintf-js/src/angular-sprintf.js' {
  declare module.exports: $Exports<'sprintf-js/src/angular-sprintf'>;
}
declare module 'sprintf-js/src/sprintf.js' {
  declare module.exports: $Exports<'sprintf-js/src/sprintf'>;
}
declare module 'sprintf-js/test/test_validation.js' {
  declare module.exports: $Exports<'sprintf-js/test/test_validation'>;
}
declare module 'sprintf-js/test/test.js' {
  declare module.exports: $Exports<'sprintf-js/test/test'>;
}
