#!/usr/bin/env bash

set -ex

if [[ ! -z "${CIRCLE_TAG}" ]]; then
  echo "Pushing install scripts to s3..."
  aws s3 cp --content-type text/plain --cache-control "max-age: 604800" ./install-standalone.sh s3://heroku-cli-assets/install-standalone.sh
  aws s3 cp --content-type text/plain --cache-control "max-age: 604800" ./install-standalone.sh s3://heroku-cli-assets/install.sh
  aws s3 cp --content-type text/plain --cache-control "max-age: 604800" ./install-ubuntu.sh s3://heroku-cli-assets/install-ubuntu.sh
else
  echo "CI workflow is not from a git version tag, skipping install scripts"
fi
