#!/usr/bin/env bash

set -ex

if [[ ! -z "${CIRCLE_TAG}" ]]; then
  aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION" --paths "/*"
elif [[ "$CIRCLE_BRANCH" == "master" ]]; then
  aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION" --paths "/channels/beta/*"
else
  echo "Not on stable or beta release, skipping invalidate cdn cache"
fi
