#!/usr/bin/env bash

set -ex

RELEASE_PREFIX="release-"
PRERELEASE_PREFIX="prerelease/"
TARGET_BRANCH=${GITHUB_HEAD_REF#refs/heads/}
if [[ -z $TARGET_BRANCH ]]; then
  TARGET_BRANCH=$(git rev-parse --abbrev-ref HEAD)
fi

invalidationResponse=''
if [[ "${TARGET_BRANCH}" == *"${RELEASE_PREFIX}"* ]]; then
  invalidationResponse=$(aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION" --paths "/*")
elif [[ "${TARGET_BRANCH}" == *"${PRERELEASE_PREFIX}"* ]]; then
  invalidationResponse=$(aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION" --paths "/channels/beta/*")
else
  echo "Not on stable or beta release, skipping invalidate cdn cache"
fi

if [[ "$invalidationResponse" != '' ]]; then
  invalidationId=$(echo "$invalidationResponse" |  grep Id  | awk -F'"' '{ print $4}')
  aws cloudfront wait invalidation-completed --id "$invalidationId" --distribution-id "$CLOUDFRONT_DISTRIBUTION"
fi
