#!/usr/bin/env bash

# NOTE: this will test whatever version is installed locally. Install what you want first.

# pipefail is necessary for "command not found" to throw an error in these tests.
set -e -o pipefail

declare -a COMMANDS=(
  "heroku"
  "heroku access --app particleboard-staging"
  "heroku addons --app status-ui"
  "heroku apps -p"
  "heroku apps:info --app heroku-cli-test-staging"
  "heroku auth:2fa"
  "heroku auth:whoami"
  "heroku authorizations"
  "heroku autocomplete"
  "heroku buildpacks:search ruby"
  "heroku certs --app status-ui"
  "heroku ci --app particleboard-staging"
  "heroku ci --pipeline status-ui"
  "heroku ci:config --pipeline status-ui"
  "heroku clients"
  "heroku commands"
  "heroku domains --app status-ui"
  "heroku drains --app heroku-cli-test-staging"
  "heroku features --app heroku-cli-test-staging"
  "rm -rf ~/status-ui && heroku git:clone ~/status-ui --app status-ui && rm -rf ~/status-ui" # `rm` used so it will always run locally
  "heroku help"
  "heroku --help"
  "heroku -h"
  "heroku keys"
  "heroku labs"
  "heroku local:version"
  "heroku maintenance --app heroku-cli-test-staging"
  "heroku members --team heroku-front-end"
  "heroku notifications"
  "heroku orgs"
  "heroku pg:backups --app status-ui"
  "heroku pipelines"
  "heroku plugins"
  "heroku plugins:install sudo"
  "heroku redis:info --app status-ui"
  "heroku regions"
  "heroku releases --app heroku-cli-test-staging"
  "heroku sessions"
  "heroku spaces"
  "heroku status"
  "heroku teams"
  "heroku version"
  "heroku --version"
  "heroku -v"
  "heroku which authorizations"
  "heroku whoami"
)

# todo: find a way to test these with automation
#  "heroku login"
#  "heroku logs --app status-ui"
#  "heroku config --app status-ui"
#  "heroku webhooks --app status-ui"

for cmd in "${COMMANDS[@]}"
do
  echo "\n\n\nRUNNING: $cmd"
#  todo: swallow output if sensitive info here?
  eval "$cmd"

done
