---
environment:
  nodejs_version: "8"
cache:
  - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn
test_script:
  - ./node_modules/.bin/jest

build: 'off'
