---
version: 2
jobs:
  build:
    working_directory: /cli
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-{{ .Branch }}-{{checksum "yarn.lock"}}
            - v1-yarn-{{ .Branch }}
            - v1-yarn-master
      - run: {command: "yarn"}
      - run: {command: "npx standard", when: always}
      - run: {command: "npx nyc mocha", when: always}
      - run: {command: "npx nyc report --reporter=text-lcov > coverage.lcov && bash <(curl -s https://codecov.io/bash)"}
      - save_cache:
          key: v1-yarn-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - /cli/node_modules
            - /usr/local/share/.cache/yarn
