---
version: 2
executorType: docker
containerInfo:
  - image: dickeyxxx/cli-engine-docker:v1.2.1-node7
stages:
  build:
    workDir: ~/cli
    steps:
      - type: checkout
      - type: cache-restore
        key: cli
      - type: shell
        command: |
          set -exu
          yarn config set registry https://cli-npm.heroku.com
          yarn
          # build dev only if it is a git checkout
          if [ "${CIRCLE_BRANCH}" == "dev" ] && [ ! -d ~/cli/node_modules/cli-engine/lib ] ; then
            cd ~/cli/node_modules/cli-engine && yarn && cd ~/cli
          fi
          ./bin/run version
          ./bin/run help
      - type: cache-save
        key: cli
        paths:
          - /usr/local/share/.cache/yarn
      - type: deploy
        shell: /bin/bash
        command: |
          set -e
          echo $HEROKU_DEB_KEY | base64 -d | gpg --import
          set -ex
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            TAG=`git describe --exact-match HEAD || echo NOTAG`
            if [ "${TAG}" != "NOTAG" ]; then
              yarn run release stable
              ./scripts/release-deb stable
            else
              yarn run release beta
              ./scripts/release-deb beta
            fi
          elif [ "${CIRCLE_BRANCH}" == "dev" ]; then
            yarn run release dev
            ./scripts/release-deb dev
          fi
