---
version: 2
executorType: docker
containerInfo:
  - image: dickeyxxx/cli-engine-docker:v1.3.1
stages:
  build:
    workDir: ~/cli
    steps:
      - type: checkout
      - type: cache-restore
        key: cli
      - type: shell
        command: |
          set -exu
          yarn config set registry https://cli-npm.heroku.com
          yarn
          if [ "${CIRCLE_BRANCH}" == "dev" ]; then
            cd ~/cli/node_modules/cli-engine && yarn && cd ~/cli
          fi
          ./bin/run version
          ./bin/run help
      - type: cache-save
        key: cli
        paths:
          - /usr/local/share/.cache/yarn
      - type: deploy
        shell: /bin/bash
        command: |
          set -e
          echo $HEROKU_DEB_KEY | base64 -d | gpg --import
          echo "machine api.heroku.com" >> ~/.netrc
          echo "  login jeff+devcenter@heroku.com" >> ~/.netrc
          echo "  password $HEROKU_API_KEY" >> ~/.netrc
          chmod 0600 ~/.netrc
          set -ex
          if [ "${CIRCLE_BRANCH}" == "auto-doc" ]; then
            ./scripts/generate_docs.sh > /tmp/cli_documentation.md
            devcenter push /tmp/heroku-cli-commands.md --trace
          fi
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            TAG=`git describe --exact-match HEAD || echo NOTAG`
            if [ "${TAG}" != "NOTAG" ]; then
              yarn run release stable
              ./scripts/release-deb stable
            else
              yarn run release beta
              ./scripts/release-deb beta
            fi
          elif [ "${CIRCLE_BRANCH}" == "dev" ]; then
            yarn run release dev
            ./scripts/release-deb dev
          fi
