import oclif from 'eslint-config-oclif'

export default [
  ...oclif,
  {
    ignores: [
      './dist',
      './lib',
      '**/*.js',
      '**/*.cjs',
      '**/*.mjs',
    ],
  },
  {
    files: [
      '**/*.ts',
    ],
    languageOptions: {
      parserOptions: {
        ecmaFeatures: {
          modules: true,
        },
        ecmaVersion: 6,
        sourceType: 'module',
      },
    },
    rules: {
      '@stylistic/comma-dangle': 'warn',
      '@stylistic/function-paren-newline': 'warn',
      '@stylistic/indent': 'warn',
      '@stylistic/indent-binary-ops': 'warn',
      '@stylistic/lines-between-class-members': 'warn',
      '@stylistic/multiline-ternary': 'warn',
      '@stylistic/object-curly-newline': 'warn',
      '@stylistic/object-curly-spacing': 'warn',
      '@stylistic/operator-linebreak': 'warn',
      '@stylistic/quote-props': 'warn',
      '@stylistic/quotes': 'warn',
      '@typescript-eslint/no-empty-object-type': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-require-imports': 'warn',
      '@typescript-eslint/no-unused-expressions': 'warn',
      '@typescript-eslint/no-unused-vars': 'warn',
      '@typescript-eslint/no-useless-constructor': 'warn',
      camelcase: 'warn',
      'getter-return': 'warn',
      'import/namespace': 'warn',
      'import/no-named-as-default-member': 'warn',
      'mocha/max-top-level-suites': 'warn',
      'mocha/no-exports': 'warn',
      'mocha/no-mocha-arrows': 'warn',
      'n/no-unsupported-features/node-builtins': 'warn',
      'n/no-process-exit': 'warn',
      'n/shebang': 'warn',
      'no-await-in-loop': 'warn',
      'no-negated-condition': 'warn',
      'no-promise-executor-return': 'warn',
      'no-unassigned-vars': 'warn',
      'no-undef': 'warn',
      'no-var': 'warn',
      'object-shorthand': 'warn',
      'perfectionist/sort-classes': 'warn',
      'perfectionist/sort-imports': 'warn',
      'perfectionist/sort-interfaces': 'warn',
      'perfectionist/sort-intersection-types': 'warn',
      'perfectionist/sort-named-exports': 'warn',
      'perfectionist/sort-named-imports': 'warn',
      'perfectionist/sort-object-types': 'warn',
      'perfectionist/sort-objects': 'warn',
      'perfectionist/sort-switch-case': 'warn',
      'perfectionist/sort-union-types': 'warn',
      'prefer-arrow-callback': 'warn',
      'prefer-object-spread': 'warn',
      'unicorn/consistent-function-scoping': 'warn',
      'unicorn/filename-case': 'warn',
      'unicorn/import-style': 'warn',
      'unicorn/no-anonymous-default-export': 'warn',
      'unicorn/no-array-callback-reference': 'warn',
      'unicorn/no-array-for-each': 'warn',
      'unicorn/no-array-reduce': 'warn',
      'unicorn/no-empty-file': 'warn',
      'unicorn/no-lonely-if': 'warn',
      'unicorn/no-process-exit': 'warn',
      'unicorn/no-useless-undefined': 'warn',
      'unicorn/numeric-separators-style': 'warn',
      'unicorn/prefer-event-target': 'warn',
      'unicorn/prefer-global-this': 'warn',
      'unicorn/prefer-node-protocol': 'warn',
      'unicorn/prefer-number-properties': 'warn',
      'unicorn/prefer-regexp-test': 'warn',
      'unicorn/prefer-spread': 'warn',
      'unicorn/prefer-string-raw': 'warn',
      'unicorn/prefer-string-replace-all': 'warn',
      'unicorn/prefer-structured-clone': 'warn',
      'unicorn/prefer-ternary': 'warn',
      'unicorn/throw-new-error': 'warn',
    },
  },
]
