#!/usr/bin/env bash

set -e

if [[ "${CI:-}" != "true" ]]; then
  echo "skipping github setup since not on CI"
  exit
fi

git config --global user.email "31491619+heroku-cli@users.noreply.github.com"
git config --global user.name "heroku-cli"
