#!/usr/bin/env node

// this utility script is only used for homebrew

const qq = require('qqjs')

qq.config.silent = false
qq.run(async () => {
  await require('../utils/_update_channel')()
  // this darwin target isn't used
  // but oclif-dev pack needs at least 1 target
  // to build the base tarball we need for updating homebrew
  await qq.x('./node_modules/.bin/oclif-dev pack --targets darwin-x64')
})
