#!/usr/bin/env node

// this utility script is only used for homebrew

const qq = require('qqjs')

qq.config.silent = false
qq.run(async () => {
  await require('./update_channel')()
  // this darwin target isn't used
  // but dev-cli requires at least 1 target
  // to build the base target we need from homebrew
  await qq.x('./node_modules/.bin/oclif-dev pack --targets darwin-x64')
})
