#!/usr/bin/env bash

set -ex

source ./scripts/_init

SHA256XZ=$(node -p \ " \
  require('fs'); \
  let manifest = JSON.parse(fs.readFileSync('./dist/darwin-x64')); \
  manifest.sha256xz
  ")

git clone git@github.com:heroku/homebrew-brew.git tmp/homebrew-brew
cd tmp/homebrew-brew
sed -i "s/heroku-cli-v.*-darwin-x64/heroku-cli-v${VERSION}-darwin-x64/" Formula/heroku.rb
sed -i "s/version \".*\"/version \"${VERSION}\"/" Formula/heroku.rb
sed -i "s/sha256 \".*\"/sha256 \"${SHA256XZ}\"/" Formula/heroku.rb
git add Formula/heroku.rb
git commit -m "heroku ${VERSION}"

if [[ ${CHANNEL} != "stable" ]]; then
  echo "not on stable, skipping homebrew"
  exit
fi

git push origin master
