#!/usr/bin/env bash

set +x
echo "$HEROKU_DEB_KEY" | base64 -d | gpg --import
set -x

source ./scripts/_init

CACHE_DIR="$tmp/s3"
DEB_REMOTE_BASE=s3://$S3_BUCKET/branches/$CHANNEL/apt

rm -rf "$CACHE_DIR"
mkdir -p "$CACHE_DIR"
cd "$CACHE_DIR"

# do long cache files first
for ARCH in "${DEB_ARCHS[@]}"; do
  mv "$(unversioned_deb_path)" "$CACHE_DIR/$(versioned_deb_base).deb"
done

s3uploadLongCache --recursive "$CACHE_DIR" "$DEB_REMOTE_BASE"

# create Package apt file
apt-ftparchive packages . > Packages
gzip -c Packages > Packages.gz
bzip2 -k Packages
xz -k Packages

# create Release apt file
apt-ftparchive -c "$root/resources/deb/apt-ftparchive.conf" release . > Release
gpg --digest-algo SHA512 --clearsign -u 0F1B0520 -o InRelease Release
gpg --digest-algo SHA512 -abs -u 0F1B0520 -o Release.gpg Release

# remove the deb files so we don't push them again
rm ./*.deb

s3uploadShortCache --recursive "$CACHE_DIR" "$DEB_REMOTE_BASE"
