#!/usr/bin/env bash

source ./scripts/_init

unset OS
unset ARCH

"$scripts/release/_github_setup"

set -x

echo "Releasing ${CHANNEL}"

# upload files to s3
"${scripts}/release/_upload_dist"
"${scripts}/release/_upload_debian"
"${scripts}/release/_homebrew"

# invalidate CDN
aws cloudfront create-invalidation --distribution-id EHF9FOCUJYVZ --paths "/heroku-cli/channels/$CHANNEL/*" "/branches/$CHANNEL/apt/*"
