#!/usr/bin/env bash

# builds the dev center documentation to /tmp/heroku-cli-commands.md

source ./scripts/_init

set +x
echo "$HEROKU_DEB_KEY" | base64 -d | gpg --import
cat << EOF > ~/.netrc
machine api.heroku.com
  login me@example.com
  password $HEROKU_API_KEY
EOF
chmod 0600 ~/.netrc
set -ex

yarn
./bin/run whoami
git clone https://github.com/heroku/heroku-cli-dev-center-generator.git
./bin/run plugins:link ./heroku-cli-dev-center-generator
# id `devcenter:generate` is not working
./bin/run generate > /tmp/heroku-cli-commands.md
devcenter push /tmp/heroku-cli-commands.md --trace
