#!/usr/bin/env bash

set -ex

export OS=darwin
export ARCH=x64

source ./scripts/_init

rm -rf tmp/homebrew-brew
git clone git@github.com:heroku/homebrew-brew.git tmp/homebrew-brew

REMOTE_BASE="s3://$S3_BUCKET/homebrew"
NODE_VERSION=$(node -p "require('./package.json')['cli-engine'].node || process.versions.node")
(
  NODE_TARBALL_BASE=node-${NODE_VERSION}.tar.xz
  NODE_TARBALL_PATH=$DIST_DIR/$NODE_TARBALL_BASE
  if ! grep -q "$NODE_VERSION" "tmp/homebrew-brew/Formula/heroku-node.rb"; then
    (
      rm -rf "$TMP_DIR/homebrew"
      mkdir "$TMP_DIR/homebrew"
      cd "$TMP_DIR/homebrew"
      tar -xJf "$TXZ_PATH"
      mkdir bin
      mv "$VERSIONED_BASE/bin/node" "bin/node"
      rm -rf "$VERSIONED_BASE"
      tar c bin | xz > "$NODE_TARBALL_PATH"
    )
    NODE_SHA256XZ=$(shasum -a 256 "$NODE_TARBALL_PATH" | awk \{'print $1'\})
    cd tmp/homebrew-brew
    sed -i "s/node-.*.tar.xz/${NODE_TARBALL_BASE}/" Formula/heroku-node.rb
    sed -i "s/sha256 \".*\"/sha256 \"${NODE_SHA256XZ}\"/" Formula/heroku-node.rb
    git add Formula/heroku-node.rb
    git diff --cached
    aws s3 cp --cache-control max-age=0 "$NODE_TARBALL_PATH" "$REMOTE_BASE/$NODE_TARBALL_BASE"
    git commit -m "heroku-node ${NODE_VERSION}"
    git push origin master
  fi
)

TARBALL_BASE=heroku-${SHORT_VERSION}.tar.xz
TARBALL_PATH=$DIST_DIR/$TARBALL_BASE
(
  rm -rf "$TMP_DIR/homebrew"
  mkdir "$TMP_DIR/homebrew"
  cd "$TMP_DIR/homebrew"
  tar -xJf "$TXZ_PATH"
  rm "$VERSIONED_BASE/bin/node"
  tar c "$VERSIONED_BASE" | xz > "$TARBALL_PATH"
)
SHA256XZ=$(shasum -a 256 "$TARBALL_PATH" | awk \{'print $1'\})

cd tmp/homebrew-brew
sed -i "s/heroku-.*.tar.xz/${TARBALL_BASE}/" Formula/heroku.rb
sed -i "s/sha256 \".*\"/sha256 \"${SHA256XZ}\"/" Formula/heroku.rb
git add Formula/heroku.rb
git diff --cached

if [[ ${CHANNEL} != "stable" ]]; then
  echo "not on stable, skipping homebrew"
  exit
fi

aws s3 cp --cache-control max-age=0 "$TARBALL_PATH" "$REMOTE_BASE/$TARBALL_BASE"
git commit -m "heroku ${SHORT_VERSION}"
git push origin master
