#!/usr/bin/env bash

set -ex

rm -rf tmp/homebrew-brew
git config --global core.pager cat
git clone git@github.com:heroku/homebrew-brew.git tmp/homebrew-brew
DIST_DIR=$(cd ./dist && pwd)
TMP_DIR=$(cd ./tmp && pwd)

REMOTE_BASE="s3://$S3_BUCKET/homebrew"
NODE_VERSION=$(node -p "require('./package.json').oclif.update.node.version")
SHORT_VERSION=$(node -p "require('./package.json').version")
(
  NODE_TARBALL_BASE=node-${NODE_VERSION}.tar.xz
  NODE_TARBALL_PATH=$DIST_DIR/$NODE_TARBALL_BASE
  if ! grep -q "url.*$NODE_VERSION" "tmp/homebrew-brew/Formula/heroku-node.rb"; then
    (
      rm -rf "$TMP_DIR/homebrew"
      mkdir "$TMP_DIR/homebrew"
      cd "$TMP_DIR/homebrew"
      mkdir bin
      cp "$TMP_DIR/cache/node-v${NODE_VERSION}-darwin-x64" "bin/node"
      tar c bin | xz > "$NODE_TARBALL_PATH"
    )
    NODE_SHA256XZ=$(shasum -a 256 "$NODE_TARBALL_PATH" | awk \{'print $1'\})
    cd tmp/homebrew-brew
    sed -i "s/node-.*.tar.xz/${NODE_TARBALL_BASE}/" Formula/heroku-node.rb
    sed -i "s/sha256 \".*\"/sha256 \"${NODE_SHA256XZ}\"/" Formula/heroku-node.rb
    git add Formula/heroku-node.rb
    git diff --cached
    if [[ ! -z "${CIRCLE_TAG}" ]]; then
      echo "not on stable, skipping homebrew"
      exit
    fi
    aws s3 cp --cache-control max-age=604800 "$NODE_TARBALL_PATH" "$REMOTE_BASE/$NODE_TARBALL_BASE"
    git commit -m "heroku-node ${NODE_VERSION}"
    git push origin master
  fi
)

TARBALL_BASE=heroku-v${SHORT_VERSION}.tar.xz
TARBALL_PATH=$DIST_DIR/heroku-v${SHORT_VERSION}/$TARBALL_BASE
SHA256XZ=$(shasum -a 256 "$TARBALL_PATH" | awk \{'print $1'\})

cd tmp/homebrew-brew
sed -i "s/heroku-.*.tar.xz/${TARBALL_BASE}/" Formula/heroku.rb
sed -i "s/sha256 \".*\"/sha256 \"${SHA256XZ}\"/" Formula/heroku.rb
git add Formula/heroku.rb
git diff --cached

if [[ ! -z "${CIRCLE_TAG}" ]]; then
  echo "not on stable, skipping homebrew"
  exit
fi

aws s3 cp --cache-control max-age=604800 "$TARBALL_PATH" "$REMOTE_BASE/$TARBALL_BASE"
git commit -m "heroku v${SHORT_VERSION}"
git push origin master
