#!/usr/bin/env bash

set -ex

VERSION=$(node -p "require('./packages/cli/package.json').version")

# trigger a macos installer by committing and tagging to the repo

set +x
git clone --recurse-submodules "https://x-access-token:$(./scripts/github_token.js 290530)@github.com/heroku/cli-macos-installer.git" tmp/cli-macos-installer
set -x

cd tmp/cli-macos-installer
(
  cd cli
  git checkout "$CIRCLE_SHA1"
)
git add cli

if [[ -z "${CIRCLE_TAG}" ]]; then
  echo "not on stable, skipping macos-installer trigger"
  exit
fi

git commit -m "heroku $VERSION"
git tag "v$VERSION"
git push --tags

git push -q origin master
