#!/usr/bin/env bash

export OS=darwin
export ARCH=x64

source ./scripts/release/_init

script "darwin/build"

set -x

echo "Releasing ${CHANNEL}"

s3upload "${TMP_DIR}/heroku-cli.pkg" "${REMOTE_BASE}/heroku-cli.pkg"
