#!/usr/bin/env bash

export OS=darwin
export ARCH=x64

source ./scripts/release/_init

set -x

echo "Releasing ${CHANNEL}"

"${scripts}/build/workspace"

s3upload "${tmp}/heroku-cli.pkg" "${REMOTE_BASE}/heroku-cli.pkg"
