#!/usr/bin/env bash

set -ex

./scripts/release/_github_setup

if [[ ! -z "${CIRCLE_TAG}" ]]; then
  ./scripts/release/macos_installer_trigger
  aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION" --paths "/*"
elif [[ "$CIRCLE_BRANCH" == "master" ]]; then
  aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION" --paths "/channels/beta/*"
fi
