#!/usr/bin/env node

const qq = require('qqjs')

qq.config.silent = false
qq.run(async () => {
  await require('../utils/_update_channel')()

  const shortSha = await qq.x('git rev-parse --short=7 HEAD')
  await qq.x(`./node_modules/.bin/oclif promote --deb --xz --root="./packages/cli" --version=${process.env.VERSION} --sha=${shortSha}`)
  // copy apt files to root /apt so that install-ubuntu.sh installs latest
  const origin = `s3://${process.env.HEROKU_S3_BUCKET}/channels/stable/apt/`
  const destination = `s3://${process.env.HEROKU_S3_BUCKET}/apt/`
  await qq.x(`aws s3 cp --recursive --cache-control "max-age: 604800" "${origin}" "${destination}"`)
})
