#!/usr/bin/env node

const qq = require('qqjs')

qq.config.silent = false
qq.run(async () => {
  await require('./update_channel')()
  await qq.x('./node_modules/.bin/oclif-dev pack')
  await qq.x('./node_modules/.bin/oclif-dev publish')
})
