#!/usr/bin/env node

import getVersion from '../utils/version.js'
import {run, shell, x} from '../utils/script-exec.js'

await run(async () => {
  const version = await getVersion()
  await x('./node_modules/.bin/oclif', ['pack:win'])
  await shell(`mv dist/win/heroku-v${version}-x86.exe dist/win/heroku-v${version}-x86-unsigned.exe`)
  await shell(`mv dist/win/heroku-v${version}-x64.exe dist/win/heroku-v${version}-x64-unsigned.exe`)
})
