#!/usr/bin/env node

const execa = require('execa')

const root = '/build/dist'

async function main () {
  await execa('./node_modules/.bin/oclif-dev', ['publish:win'], {
    cwd: root,
    stdio: 'inherit'
  })
}

main()
