#!/usr/bin/env bash

# shellcheck disable=SC2034

source ./scripts/_init

./scripts/circle/github_setup

CHANNEL=$(./scripts/circle/_channel)
VERSION=$(./scripts/_version)

TMP_DIR="$root/tmp"

REMOTE_BASE="s3://$S3_BUCKET/heroku-cli/channels/$CHANNEL"
