#!/usr/bin/env bash

source ./scripts/main

yarn install --pure-lockfile
yarn check

# build only if it is a git checkout
if [ ! -d "${root}/node_modules/cli-engine/lib" ]; then
  cd "${root}/node_modules/cli-engine" && yarn && cd ~/cli
fi
