#!/usr/bin/env bash

source ./scripts/circle/_init

set -x

echo "Building ${OS} ${ARCH} ${CHANNEL}"

# first build the workspace
"${root}/scripts/build/workspace"

# now build the tarballs and installers in parallel
bg "${root}/scripts/build/tarballs"
if [[ "${OS}" = "windows" ]]; then
  bg "${root}/scripts/windows/release"
fi
wait_all
