#!/usr/bin/env bash

if [[ "${CHANNEL:-}" != "" ]]; then
  echo "${CHANNEL}"
elif [[ "${CIRCLE_TAG:-}" != "" ]]; then
  echo stable
elif [[ "${CIRCLE_BRANCH:-}" == "master" ]]; then
  echo beta
elif [[ "${CIRCLE_BRANCH:-}" == "dev" ]]; then
  echo dev
else
  echo dev
fi
