#!/usr/bin/env bash

source ./scripts/_init

if [[ "${CIRCLECI:-}" != "true" ]]; then
  echo "skipping github setup since not on circle"
  exit
fi

git config --global user.email "31491619+heroku-cli@users.noreply.github.com"
git config --global user.name "heroku-cli"
