#!/usr/bin/env bash

source ./scripts/main

set -x

echo "Releasing ${CHANNEL}"

"${root}/scripts/darwin/build"

REMOTE_BASE="s3://$S3_BUCKET/heroku-cli/channels/$CHANNEL"
s3uploadHourCache "${root}/tmp/heroku-cli.pkg" "${REMOTE_BASE}/heroku-cli.pkg"
