#!/usr/bin/env bash

source ./scripts/main
source ./scripts/circle/vars
./scripts/circle/github_setup

set -x

echo "Releasing ${CHANNEL}"

# first build the base
"${root}/scripts/build_base"

# now build the installers and tarballs in parallel
bg "${root}/scripts/build_tarballs"
if [[ "${OS}" = "windows" ]]; then
  bg "${root}/scripts/windows/release"
fi
wait_all

# finally, release to s3
"${root}/scripts/release_tarballs" dist/tarballs

if [[ "${OS}" = "darwin" ]]; then
  "${root}/scripts/darwin/homebrew"
fi
