#!/usr/bin/env bash

# shellcheck disable=SC2034

source ./scripts/main

go_home

if [[ ! -z "${CIRCLE_JOB-}" ]]; then
  IFS='_' read -ra _circle_job <<< "$CIRCLE_JOB"
  OS=${OS:-${_circle_job[0]-}}
  ARCH=${ARCH:-${_circle_job[1]-}}
fi

CHANNEL=$(./scripts/circle/channel)
VERSION=$(./scripts/version)
NODE_VERSION=$(node -p "require('./package.json')['cli-engine'].node || process.versions.node")
BASE="heroku-cli-v${VERSION}-${OS}-${ARCH}"
BUILD_DIR="${root}/tmp/builds"
TARBALL_BASE_DIR="$BUILD_DIR/${OS}_${ARCH}"
REMOTE_BASE="s3://$S3_BUCKET/heroku-cli/channels/$CHANNEL"
TGZ_PATH="$BUILD_DIR/$BASE.tar.gz"
TXZ_PATH="$BUILD_DIR/$BASE.tar.xz"
