// flow-typed signature: fb725e11fac50571d02711f11fe9c64c
// flow-typed version: <<STUB>>/cli-engine_v4.2.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cli-engine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cli-engine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cli-engine/lib/analytics' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/cli' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/commands/commands' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/commands/help' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/commands/index' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/commands/plugins/index' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/commands/plugins/install' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/commands/plugins/link' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/commands/plugins/uninstall' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/commands/plugins/update' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/commands/update' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/commands/version' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/commands/which' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/dispatcher' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/fs' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/hooks' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/linewrap' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/lock' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/not_found' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/plugins/builtin' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/plugins/cache' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/plugins/core' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/plugins/index' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/plugins/legacy' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/plugins/linked' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/plugins/manager' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/plugins/migrator' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/plugins/plugin' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/plugins/user' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/plugins/yarn' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/updater' {
  declare module.exports: any;
}

declare module 'cli-engine/lib/util' {
  declare module.exports: any;
}

declare module 'cli-engine/yarn/yarn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cli-engine/lib/analytics.js' {
  declare module.exports: $Exports<'cli-engine/lib/analytics'>;
}
declare module 'cli-engine/lib/cli.js' {
  declare module.exports: $Exports<'cli-engine/lib/cli'>;
}
declare module 'cli-engine/lib/commands/commands.js' {
  declare module.exports: $Exports<'cli-engine/lib/commands/commands'>;
}
declare module 'cli-engine/lib/commands/help.js' {
  declare module.exports: $Exports<'cli-engine/lib/commands/help'>;
}
declare module 'cli-engine/lib/commands/index.js' {
  declare module.exports: $Exports<'cli-engine/lib/commands/index'>;
}
declare module 'cli-engine/lib/commands/plugins/index.js' {
  declare module.exports: $Exports<'cli-engine/lib/commands/plugins/index'>;
}
declare module 'cli-engine/lib/commands/plugins/install.js' {
  declare module.exports: $Exports<'cli-engine/lib/commands/plugins/install'>;
}
declare module 'cli-engine/lib/commands/plugins/link.js' {
  declare module.exports: $Exports<'cli-engine/lib/commands/plugins/link'>;
}
declare module 'cli-engine/lib/commands/plugins/uninstall.js' {
  declare module.exports: $Exports<'cli-engine/lib/commands/plugins/uninstall'>;
}
declare module 'cli-engine/lib/commands/plugins/update.js' {
  declare module.exports: $Exports<'cli-engine/lib/commands/plugins/update'>;
}
declare module 'cli-engine/lib/commands/update.js' {
  declare module.exports: $Exports<'cli-engine/lib/commands/update'>;
}
declare module 'cli-engine/lib/commands/version.js' {
  declare module.exports: $Exports<'cli-engine/lib/commands/version'>;
}
declare module 'cli-engine/lib/commands/which.js' {
  declare module.exports: $Exports<'cli-engine/lib/commands/which'>;
}
declare module 'cli-engine/lib/dispatcher.js' {
  declare module.exports: $Exports<'cli-engine/lib/dispatcher'>;
}
declare module 'cli-engine/lib/fs.js' {
  declare module.exports: $Exports<'cli-engine/lib/fs'>;
}
declare module 'cli-engine/lib/hooks.js' {
  declare module.exports: $Exports<'cli-engine/lib/hooks'>;
}
declare module 'cli-engine/lib/linewrap.js' {
  declare module.exports: $Exports<'cli-engine/lib/linewrap'>;
}
declare module 'cli-engine/lib/lock.js' {
  declare module.exports: $Exports<'cli-engine/lib/lock'>;
}
declare module 'cli-engine/lib/not_found.js' {
  declare module.exports: $Exports<'cli-engine/lib/not_found'>;
}
declare module 'cli-engine/lib/plugins/builtin.js' {
  declare module.exports: $Exports<'cli-engine/lib/plugins/builtin'>;
}
declare module 'cli-engine/lib/plugins/cache.js' {
  declare module.exports: $Exports<'cli-engine/lib/plugins/cache'>;
}
declare module 'cli-engine/lib/plugins/core.js' {
  declare module.exports: $Exports<'cli-engine/lib/plugins/core'>;
}
declare module 'cli-engine/lib/plugins/index.js' {
  declare module.exports: $Exports<'cli-engine/lib/plugins/index'>;
}
declare module 'cli-engine/lib/plugins/legacy.js' {
  declare module.exports: $Exports<'cli-engine/lib/plugins/legacy'>;
}
declare module 'cli-engine/lib/plugins/linked.js' {
  declare module.exports: $Exports<'cli-engine/lib/plugins/linked'>;
}
declare module 'cli-engine/lib/plugins/manager.js' {
  declare module.exports: $Exports<'cli-engine/lib/plugins/manager'>;
}
declare module 'cli-engine/lib/plugins/migrator.js' {
  declare module.exports: $Exports<'cli-engine/lib/plugins/migrator'>;
}
declare module 'cli-engine/lib/plugins/plugin.js' {
  declare module.exports: $Exports<'cli-engine/lib/plugins/plugin'>;
}
declare module 'cli-engine/lib/plugins/user.js' {
  declare module.exports: $Exports<'cli-engine/lib/plugins/user'>;
}
declare module 'cli-engine/lib/plugins/yarn.js' {
  declare module.exports: $Exports<'cli-engine/lib/plugins/yarn'>;
}
declare module 'cli-engine/lib/updater.js' {
  declare module.exports: $Exports<'cli-engine/lib/updater'>;
}
declare module 'cli-engine/lib/util.js' {
  declare module.exports: $Exports<'cli-engine/lib/util'>;
}
declare module 'cli-engine/yarn/yarn.js' {
  declare module.exports: $Exports<'cli-engine/yarn/yarn'>;
}
