// flow-typed signature: fda85d1fb0e203a3b2af30e065c943f1
// flow-typed version: <<STUB>>/heroku-cli-status_v4.0.4/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-cli-status'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-cli-status' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-cli-status/lib/commands/status' {
  declare module.exports: any;
}

declare module 'heroku-cli-status/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-cli-status/lib/commands/status.js' {
  declare module.exports: $Exports<'heroku-cli-status/lib/commands/status'>;
}
declare module 'heroku-cli-status/lib/index.js' {
  declare module.exports: $Exports<'heroku-cli-status/lib/index'>;
}
