// flow-typed signature: 10a882b11c039d1bca82f23c66a2092c
// flow-typed version: <<STUB>>/heroku-apps_v2.4.11/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-apps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-apps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-apps/lib/buildpacks' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/apps/create' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/apps/destroy' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/apps/errors' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/apps/favorites/add' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/apps/favorites/index' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/apps/favorites/remove' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/apps/index' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/apps/info' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/apps/open' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/apps/rename' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/apps/stacks/index' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/apps/stacks/set' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/auth/2fa/disable' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/auth/2fa/generate' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/auth/2fa/index' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/auth/login' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/auth/logout' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/auth/token' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/auth/whoami' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/buildpacks/add' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/buildpacks/clear' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/buildpacks/index' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/buildpacks/remove' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/buildpacks/set' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/config/get' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/config/index' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/config/set' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/config/unset' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/dashboard' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/domains/add' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/domains/clear' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/domains/index' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/domains/remove' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/domains/wait' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/drains/add' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/drains/index' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/drains/remove' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/features/disable' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/features/enable' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/features/index' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/features/info' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/keys/add' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/keys/clear' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/keys/index' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/keys/remove' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/labs/disable' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/labs/enable' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/labs/index' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/labs/info' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/maintenance/index' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/maintenance/off' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/maintenance/on' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/notifications/index' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/ps/index' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/ps/restart' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/ps/scale' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/ps/stop' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/ps/type' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/regions/index' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/releases/index' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/releases/info' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/releases/output' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/commands/releases/rollback' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/domains_wait' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/error_info' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/git' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/index' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/output' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/push' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/releases' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/status_helper' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/time' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/two_factor_toggle' {
  declare module.exports: any;
}

declare module 'heroku-apps/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-apps/lib/buildpacks.js' {
  declare module.exports: $Exports<'heroku-apps/lib/buildpacks'>;
}
declare module 'heroku-apps/lib/commands/apps/create.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/apps/create'>;
}
declare module 'heroku-apps/lib/commands/apps/destroy.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/apps/destroy'>;
}
declare module 'heroku-apps/lib/commands/apps/errors.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/apps/errors'>;
}
declare module 'heroku-apps/lib/commands/apps/favorites/add.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/apps/favorites/add'>;
}
declare module 'heroku-apps/lib/commands/apps/favorites/index.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/apps/favorites/index'>;
}
declare module 'heroku-apps/lib/commands/apps/favorites/remove.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/apps/favorites/remove'>;
}
declare module 'heroku-apps/lib/commands/apps/index.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/apps/index'>;
}
declare module 'heroku-apps/lib/commands/apps/info.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/apps/info'>;
}
declare module 'heroku-apps/lib/commands/apps/open.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/apps/open'>;
}
declare module 'heroku-apps/lib/commands/apps/rename.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/apps/rename'>;
}
declare module 'heroku-apps/lib/commands/apps/stacks/index.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/apps/stacks/index'>;
}
declare module 'heroku-apps/lib/commands/apps/stacks/set.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/apps/stacks/set'>;
}
declare module 'heroku-apps/lib/commands/auth/2fa/disable.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/auth/2fa/disable'>;
}
declare module 'heroku-apps/lib/commands/auth/2fa/generate.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/auth/2fa/generate'>;
}
declare module 'heroku-apps/lib/commands/auth/2fa/index.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/auth/2fa/index'>;
}
declare module 'heroku-apps/lib/commands/auth/login.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/auth/login'>;
}
declare module 'heroku-apps/lib/commands/auth/logout.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/auth/logout'>;
}
declare module 'heroku-apps/lib/commands/auth/token.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/auth/token'>;
}
declare module 'heroku-apps/lib/commands/auth/whoami.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/auth/whoami'>;
}
declare module 'heroku-apps/lib/commands/buildpacks/add.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/buildpacks/add'>;
}
declare module 'heroku-apps/lib/commands/buildpacks/clear.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/buildpacks/clear'>;
}
declare module 'heroku-apps/lib/commands/buildpacks/index.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/buildpacks/index'>;
}
declare module 'heroku-apps/lib/commands/buildpacks/remove.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/buildpacks/remove'>;
}
declare module 'heroku-apps/lib/commands/buildpacks/set.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/buildpacks/set'>;
}
declare module 'heroku-apps/lib/commands/config/get.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/config/get'>;
}
declare module 'heroku-apps/lib/commands/config/index.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/config/index'>;
}
declare module 'heroku-apps/lib/commands/config/set.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/config/set'>;
}
declare module 'heroku-apps/lib/commands/config/unset.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/config/unset'>;
}
declare module 'heroku-apps/lib/commands/dashboard.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/dashboard'>;
}
declare module 'heroku-apps/lib/commands/domains/add.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/domains/add'>;
}
declare module 'heroku-apps/lib/commands/domains/clear.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/domains/clear'>;
}
declare module 'heroku-apps/lib/commands/domains/index.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/domains/index'>;
}
declare module 'heroku-apps/lib/commands/domains/remove.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/domains/remove'>;
}
declare module 'heroku-apps/lib/commands/domains/wait.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/domains/wait'>;
}
declare module 'heroku-apps/lib/commands/drains/add.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/drains/add'>;
}
declare module 'heroku-apps/lib/commands/drains/index.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/drains/index'>;
}
declare module 'heroku-apps/lib/commands/drains/remove.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/drains/remove'>;
}
declare module 'heroku-apps/lib/commands/features/disable.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/features/disable'>;
}
declare module 'heroku-apps/lib/commands/features/enable.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/features/enable'>;
}
declare module 'heroku-apps/lib/commands/features/index.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/features/index'>;
}
declare module 'heroku-apps/lib/commands/features/info.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/features/info'>;
}
declare module 'heroku-apps/lib/commands/keys/add.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/keys/add'>;
}
declare module 'heroku-apps/lib/commands/keys/clear.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/keys/clear'>;
}
declare module 'heroku-apps/lib/commands/keys/index.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/keys/index'>;
}
declare module 'heroku-apps/lib/commands/keys/remove.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/keys/remove'>;
}
declare module 'heroku-apps/lib/commands/labs/disable.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/labs/disable'>;
}
declare module 'heroku-apps/lib/commands/labs/enable.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/labs/enable'>;
}
declare module 'heroku-apps/lib/commands/labs/index.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/labs/index'>;
}
declare module 'heroku-apps/lib/commands/labs/info.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/labs/info'>;
}
declare module 'heroku-apps/lib/commands/maintenance/index.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/maintenance/index'>;
}
declare module 'heroku-apps/lib/commands/maintenance/off.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/maintenance/off'>;
}
declare module 'heroku-apps/lib/commands/maintenance/on.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/maintenance/on'>;
}
declare module 'heroku-apps/lib/commands/notifications/index.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/notifications/index'>;
}
declare module 'heroku-apps/lib/commands/ps/index.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/ps/index'>;
}
declare module 'heroku-apps/lib/commands/ps/restart.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/ps/restart'>;
}
declare module 'heroku-apps/lib/commands/ps/scale.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/ps/scale'>;
}
declare module 'heroku-apps/lib/commands/ps/stop.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/ps/stop'>;
}
declare module 'heroku-apps/lib/commands/ps/type.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/ps/type'>;
}
declare module 'heroku-apps/lib/commands/regions/index.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/regions/index'>;
}
declare module 'heroku-apps/lib/commands/releases/index.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/releases/index'>;
}
declare module 'heroku-apps/lib/commands/releases/info.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/releases/info'>;
}
declare module 'heroku-apps/lib/commands/releases/output.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/releases/output'>;
}
declare module 'heroku-apps/lib/commands/releases/rollback.js' {
  declare module.exports: $Exports<'heroku-apps/lib/commands/releases/rollback'>;
}
declare module 'heroku-apps/lib/domains_wait.js' {
  declare module.exports: $Exports<'heroku-apps/lib/domains_wait'>;
}
declare module 'heroku-apps/lib/error_info.js' {
  declare module.exports: $Exports<'heroku-apps/lib/error_info'>;
}
declare module 'heroku-apps/lib/git.js' {
  declare module.exports: $Exports<'heroku-apps/lib/git'>;
}
declare module 'heroku-apps/lib/index.js' {
  declare module.exports: $Exports<'heroku-apps/lib/index'>;
}
declare module 'heroku-apps/lib/output.js' {
  declare module.exports: $Exports<'heroku-apps/lib/output'>;
}
declare module 'heroku-apps/lib/push.js' {
  declare module.exports: $Exports<'heroku-apps/lib/push'>;
}
declare module 'heroku-apps/lib/releases.js' {
  declare module.exports: $Exports<'heroku-apps/lib/releases'>;
}
declare module 'heroku-apps/lib/status_helper.js' {
  declare module.exports: $Exports<'heroku-apps/lib/status_helper'>;
}
declare module 'heroku-apps/lib/time.js' {
  declare module.exports: $Exports<'heroku-apps/lib/time'>;
}
declare module 'heroku-apps/lib/two_factor_toggle.js' {
  declare module.exports: $Exports<'heroku-apps/lib/two_factor_toggle'>;
}
declare module 'heroku-apps/lib/util.js' {
  declare module.exports: $Exports<'heroku-apps/lib/util'>;
}
