// flow-typed signature: 125f2aa20c86eac2f11af4e435a3fbab
// flow-typed version: <<STUB>>/heroku-ps-exec_v2.2.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-ps-exec'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-ps-exec' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-ps-exec/commands/copy' {
  declare module.exports: any;
}

declare module 'heroku-ps-exec/commands/port' {
  declare module.exports: any;
}

declare module 'heroku-ps-exec/commands/socks' {
  declare module.exports: any;
}

declare module 'heroku-ps-exec/commands/ssh' {
  declare module.exports: any;
}

declare module 'heroku-ps-exec/commands/status' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-ps-exec/commands/copy.js' {
  declare module.exports: $Exports<'heroku-ps-exec/commands/copy'>;
}
declare module 'heroku-ps-exec/commands/port.js' {
  declare module.exports: $Exports<'heroku-ps-exec/commands/port'>;
}
declare module 'heroku-ps-exec/commands/socks.js' {
  declare module.exports: $Exports<'heroku-ps-exec/commands/socks'>;
}
declare module 'heroku-ps-exec/commands/ssh.js' {
  declare module.exports: $Exports<'heroku-ps-exec/commands/ssh'>;
}
declare module 'heroku-ps-exec/commands/status.js' {
  declare module.exports: $Exports<'heroku-ps-exec/commands/status'>;
}
declare module 'heroku-ps-exec/index' {
  declare module.exports: $Exports<'heroku-ps-exec'>;
}
declare module 'heroku-ps-exec/index.js' {
  declare module.exports: $Exports<'heroku-ps-exec'>;
}
