// flow-typed signature: ac015873556eeba0a762ad27d7ff5da7
// flow-typed version: <<STUB>>/heroku-fork_v4.1.25/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-fork'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-fork' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-fork/commands/fork' {
  declare module.exports: any;
}

declare module 'heroku-fork/lib/addons' {
  declare module.exports: any;
}

declare module 'heroku-fork/lib/apps' {
  declare module.exports: any;
}

declare module 'heroku-fork/lib/postgres' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-fork/commands/fork.js' {
  declare module.exports: $Exports<'heroku-fork/commands/fork'>;
}
declare module 'heroku-fork/index' {
  declare module.exports: $Exports<'heroku-fork'>;
}
declare module 'heroku-fork/index.js' {
  declare module.exports: $Exports<'heroku-fork'>;
}
declare module 'heroku-fork/lib/addons.js' {
  declare module.exports: $Exports<'heroku-fork/lib/addons'>;
}
declare module 'heroku-fork/lib/apps.js' {
  declare module.exports: $Exports<'heroku-fork/lib/apps'>;
}
declare module 'heroku-fork/lib/postgres.js' {
  declare module.exports: $Exports<'heroku-fork/lib/postgres'>;
}
