// flow-typed signature: 34145fe5de0aae1e99c98367a736ab0e
// flow-typed version: <<STUB>>/heroku-cli-oauth_v2.0.14/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-cli-oauth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-cli-oauth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-cli-oauth/commands/authorizations/create' {
  declare module.exports: any;
}

declare module 'heroku-cli-oauth/commands/authorizations/index' {
  declare module.exports: any;
}

declare module 'heroku-cli-oauth/commands/authorizations/info' {
  declare module.exports: any;
}

declare module 'heroku-cli-oauth/commands/authorizations/revoke' {
  declare module.exports: any;
}

declare module 'heroku-cli-oauth/commands/authorizations/update' {
  declare module.exports: any;
}

declare module 'heroku-cli-oauth/commands/clients/create' {
  declare module.exports: any;
}

declare module 'heroku-cli-oauth/commands/clients/destroy' {
  declare module.exports: any;
}

declare module 'heroku-cli-oauth/commands/clients/index' {
  declare module.exports: any;
}

declare module 'heroku-cli-oauth/commands/clients/info' {
  declare module.exports: any;
}

declare module 'heroku-cli-oauth/commands/clients/update' {
  declare module.exports: any;
}

declare module 'heroku-cli-oauth/commands/sessions/destroy' {
  declare module.exports: any;
}

declare module 'heroku-cli-oauth/commands/sessions/index' {
  declare module.exports: any;
}

declare module 'heroku-cli-oauth/lib/authorizations' {
  declare module.exports: any;
}

declare module 'heroku-cli-oauth/lib/clients' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-cli-oauth/commands/authorizations/create.js' {
  declare module.exports: $Exports<'heroku-cli-oauth/commands/authorizations/create'>;
}
declare module 'heroku-cli-oauth/commands/authorizations/index.js' {
  declare module.exports: $Exports<'heroku-cli-oauth/commands/authorizations/index'>;
}
declare module 'heroku-cli-oauth/commands/authorizations/info.js' {
  declare module.exports: $Exports<'heroku-cli-oauth/commands/authorizations/info'>;
}
declare module 'heroku-cli-oauth/commands/authorizations/revoke.js' {
  declare module.exports: $Exports<'heroku-cli-oauth/commands/authorizations/revoke'>;
}
declare module 'heroku-cli-oauth/commands/authorizations/update.js' {
  declare module.exports: $Exports<'heroku-cli-oauth/commands/authorizations/update'>;
}
declare module 'heroku-cli-oauth/commands/clients/create.js' {
  declare module.exports: $Exports<'heroku-cli-oauth/commands/clients/create'>;
}
declare module 'heroku-cli-oauth/commands/clients/destroy.js' {
  declare module.exports: $Exports<'heroku-cli-oauth/commands/clients/destroy'>;
}
declare module 'heroku-cli-oauth/commands/clients/index.js' {
  declare module.exports: $Exports<'heroku-cli-oauth/commands/clients/index'>;
}
declare module 'heroku-cli-oauth/commands/clients/info.js' {
  declare module.exports: $Exports<'heroku-cli-oauth/commands/clients/info'>;
}
declare module 'heroku-cli-oauth/commands/clients/update.js' {
  declare module.exports: $Exports<'heroku-cli-oauth/commands/clients/update'>;
}
declare module 'heroku-cli-oauth/commands/sessions/destroy.js' {
  declare module.exports: $Exports<'heroku-cli-oauth/commands/sessions/destroy'>;
}
declare module 'heroku-cli-oauth/commands/sessions/index.js' {
  declare module.exports: $Exports<'heroku-cli-oauth/commands/sessions/index'>;
}
declare module 'heroku-cli-oauth/index' {
  declare module.exports: $Exports<'heroku-cli-oauth'>;
}
declare module 'heroku-cli-oauth/index.js' {
  declare module.exports: $Exports<'heroku-cli-oauth'>;
}
declare module 'heroku-cli-oauth/lib/authorizations.js' {
  declare module.exports: $Exports<'heroku-cli-oauth/lib/authorizations'>;
}
declare module 'heroku-cli-oauth/lib/clients.js' {
  declare module.exports: $Exports<'heroku-cli-oauth/lib/clients'>;
}
