// flow-typed signature: 513a869b1c91ad4c315854bdd65364d6
// flow-typed version: <<STUB>>/heroku-git_v2.5.21/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-git'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-git' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-git/commands/git/clone' {
  declare module.exports: any;
}

declare module 'heroku-git/commands/git/remote' {
  declare module.exports: any;
}

declare module 'heroku-git/lib/git' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-git/commands/git/clone.js' {
  declare module.exports: $Exports<'heroku-git/commands/git/clone'>;
}
declare module 'heroku-git/commands/git/remote.js' {
  declare module.exports: $Exports<'heroku-git/commands/git/remote'>;
}
declare module 'heroku-git/index' {
  declare module.exports: $Exports<'heroku-git'>;
}
declare module 'heroku-git/index.js' {
  declare module.exports: $Exports<'heroku-git'>;
}
declare module 'heroku-git/lib/git.js' {
  declare module.exports: $Exports<'heroku-git/lib/git'>;
}
