// flow-typed signature: 427197c75496e014590d83c1ce9727ca
// flow-typed version: <<STUB>>/heroku-ci_v1.9.5/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-ci'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-ci' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-ci/commands/ci/config-get' {
  declare module.exports: any;
}

declare module 'heroku-ci/commands/ci/config-index' {
  declare module.exports: any;
}

declare module 'heroku-ci/commands/ci/config-set' {
  declare module.exports: any;
}

declare module 'heroku-ci/commands/ci/config-unset' {
  declare module.exports: any;
}

declare module 'heroku-ci/commands/ci/debug' {
  declare module.exports: any;
}

declare module 'heroku-ci/commands/ci/index' {
  declare module.exports: any;
}

declare module 'heroku-ci/commands/ci/info' {
  declare module.exports: any;
}

declare module 'heroku-ci/commands/ci/last' {
  declare module.exports: any;
}

declare module 'heroku-ci/commands/ci/migrate-manifest' {
  declare module.exports: any;
}

declare module 'heroku-ci/commands/ci/open' {
  declare module.exports: any;
}

declare module 'heroku-ci/commands/ci/rerun' {
  declare module.exports: any;
}

declare module 'heroku-ci/commands/ci/run' {
  declare module.exports: any;
}

declare module 'heroku-ci/lib/git' {
  declare module.exports: any;
}

declare module 'heroku-ci/lib/heroku-api' {
  declare module.exports: any;
}

declare module 'heroku-ci/lib/render-test-runs' {
  declare module.exports: any;
}

declare module 'heroku-ci/lib/source' {
  declare module.exports: any;
}

declare module 'heroku-ci/lib/test-run-states-util' {
  declare module.exports: any;
}

declare module 'heroku-ci/lib/test-run-states' {
  declare module.exports: any;
}

declare module 'heroku-ci/lib/test-run' {
  declare module.exports: any;
}

declare module 'heroku-ci/lib/utils' {
  declare module.exports: any;
}

declare module 'heroku-ci/test/commands/ci/config-get-test' {
  declare module.exports: any;
}

declare module 'heroku-ci/test/commands/ci/config-index-test' {
  declare module.exports: any;
}

declare module 'heroku-ci/test/commands/ci/config-set-test' {
  declare module.exports: any;
}

declare module 'heroku-ci/test/commands/ci/config-unset-test' {
  declare module.exports: any;
}

declare module 'heroku-ci/test/commands/ci/index-test' {
  declare module.exports: any;
}

declare module 'heroku-ci/test/commands/ci/last-test' {
  declare module.exports: any;
}

declare module 'heroku-ci/test/lib/factory' {
  declare module.exports: any;
}

declare module 'heroku-ci/test/lib/heroku-api-test' {
  declare module.exports: any;
}

declare module 'heroku-ci/test/lib/utils-test' {
  declare module.exports: any;
}

declare module 'heroku-ci/test/test-setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-ci/commands/ci/config-get.js' {
  declare module.exports: $Exports<'heroku-ci/commands/ci/config-get'>;
}
declare module 'heroku-ci/commands/ci/config-index.js' {
  declare module.exports: $Exports<'heroku-ci/commands/ci/config-index'>;
}
declare module 'heroku-ci/commands/ci/config-set.js' {
  declare module.exports: $Exports<'heroku-ci/commands/ci/config-set'>;
}
declare module 'heroku-ci/commands/ci/config-unset.js' {
  declare module.exports: $Exports<'heroku-ci/commands/ci/config-unset'>;
}
declare module 'heroku-ci/commands/ci/debug.js' {
  declare module.exports: $Exports<'heroku-ci/commands/ci/debug'>;
}
declare module 'heroku-ci/commands/ci/index.js' {
  declare module.exports: $Exports<'heroku-ci/commands/ci/index'>;
}
declare module 'heroku-ci/commands/ci/info.js' {
  declare module.exports: $Exports<'heroku-ci/commands/ci/info'>;
}
declare module 'heroku-ci/commands/ci/last.js' {
  declare module.exports: $Exports<'heroku-ci/commands/ci/last'>;
}
declare module 'heroku-ci/commands/ci/migrate-manifest.js' {
  declare module.exports: $Exports<'heroku-ci/commands/ci/migrate-manifest'>;
}
declare module 'heroku-ci/commands/ci/open.js' {
  declare module.exports: $Exports<'heroku-ci/commands/ci/open'>;
}
declare module 'heroku-ci/commands/ci/rerun.js' {
  declare module.exports: $Exports<'heroku-ci/commands/ci/rerun'>;
}
declare module 'heroku-ci/commands/ci/run.js' {
  declare module.exports: $Exports<'heroku-ci/commands/ci/run'>;
}
declare module 'heroku-ci/index' {
  declare module.exports: $Exports<'heroku-ci'>;
}
declare module 'heroku-ci/index.js' {
  declare module.exports: $Exports<'heroku-ci'>;
}
declare module 'heroku-ci/lib/git.js' {
  declare module.exports: $Exports<'heroku-ci/lib/git'>;
}
declare module 'heroku-ci/lib/heroku-api.js' {
  declare module.exports: $Exports<'heroku-ci/lib/heroku-api'>;
}
declare module 'heroku-ci/lib/render-test-runs.js' {
  declare module.exports: $Exports<'heroku-ci/lib/render-test-runs'>;
}
declare module 'heroku-ci/lib/source.js' {
  declare module.exports: $Exports<'heroku-ci/lib/source'>;
}
declare module 'heroku-ci/lib/test-run-states-util.js' {
  declare module.exports: $Exports<'heroku-ci/lib/test-run-states-util'>;
}
declare module 'heroku-ci/lib/test-run-states.js' {
  declare module.exports: $Exports<'heroku-ci/lib/test-run-states'>;
}
declare module 'heroku-ci/lib/test-run.js' {
  declare module.exports: $Exports<'heroku-ci/lib/test-run'>;
}
declare module 'heroku-ci/lib/utils.js' {
  declare module.exports: $Exports<'heroku-ci/lib/utils'>;
}
declare module 'heroku-ci/test/commands/ci/config-get-test.js' {
  declare module.exports: $Exports<'heroku-ci/test/commands/ci/config-get-test'>;
}
declare module 'heroku-ci/test/commands/ci/config-index-test.js' {
  declare module.exports: $Exports<'heroku-ci/test/commands/ci/config-index-test'>;
}
declare module 'heroku-ci/test/commands/ci/config-set-test.js' {
  declare module.exports: $Exports<'heroku-ci/test/commands/ci/config-set-test'>;
}
declare module 'heroku-ci/test/commands/ci/config-unset-test.js' {
  declare module.exports: $Exports<'heroku-ci/test/commands/ci/config-unset-test'>;
}
declare module 'heroku-ci/test/commands/ci/index-test.js' {
  declare module.exports: $Exports<'heroku-ci/test/commands/ci/index-test'>;
}
declare module 'heroku-ci/test/commands/ci/last-test.js' {
  declare module.exports: $Exports<'heroku-ci/test/commands/ci/last-test'>;
}
declare module 'heroku-ci/test/lib/factory.js' {
  declare module.exports: $Exports<'heroku-ci/test/lib/factory'>;
}
declare module 'heroku-ci/test/lib/heroku-api-test.js' {
  declare module.exports: $Exports<'heroku-ci/test/lib/heroku-api-test'>;
}
declare module 'heroku-ci/test/lib/utils-test.js' {
  declare module.exports: $Exports<'heroku-ci/test/lib/utils-test'>;
}
declare module 'heroku-ci/test/test-setup.js' {
  declare module.exports: $Exports<'heroku-ci/test/test-setup'>;
}
