// flow-typed signature: 00fbab65da222f5be41ce2f3798ac7c5
// flow-typed version: <<STUB>>/heroku-redis_v1.2.15/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-redis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-redis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-redis/commands/cli' {
  declare module.exports: any;
}

declare module 'heroku-redis/commands/credentials' {
  declare module.exports: any;
}

declare module 'heroku-redis/commands/index' {
  declare module.exports: any;
}

declare module 'heroku-redis/commands/info' {
  declare module.exports: any;
}

declare module 'heroku-redis/commands/maintenance' {
  declare module.exports: any;
}

declare module 'heroku-redis/commands/maxmemory' {
  declare module.exports: any;
}

declare module 'heroku-redis/commands/promote' {
  declare module.exports: any;
}

declare module 'heroku-redis/commands/timeout' {
  declare module.exports: any;
}

declare module 'heroku-redis/commands/wait' {
  declare module.exports: any;
}

declare module 'heroku-redis/lib/shared' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-redis/commands/cli.js' {
  declare module.exports: $Exports<'heroku-redis/commands/cli'>;
}
declare module 'heroku-redis/commands/credentials.js' {
  declare module.exports: $Exports<'heroku-redis/commands/credentials'>;
}
declare module 'heroku-redis/commands/index.js' {
  declare module.exports: $Exports<'heroku-redis/commands/index'>;
}
declare module 'heroku-redis/commands/info.js' {
  declare module.exports: $Exports<'heroku-redis/commands/info'>;
}
declare module 'heroku-redis/commands/maintenance.js' {
  declare module.exports: $Exports<'heroku-redis/commands/maintenance'>;
}
declare module 'heroku-redis/commands/maxmemory.js' {
  declare module.exports: $Exports<'heroku-redis/commands/maxmemory'>;
}
declare module 'heroku-redis/commands/promote.js' {
  declare module.exports: $Exports<'heroku-redis/commands/promote'>;
}
declare module 'heroku-redis/commands/timeout.js' {
  declare module.exports: $Exports<'heroku-redis/commands/timeout'>;
}
declare module 'heroku-redis/commands/wait.js' {
  declare module.exports: $Exports<'heroku-redis/commands/wait'>;
}
declare module 'heroku-redis/index' {
  declare module.exports: $Exports<'heroku-redis'>;
}
declare module 'heroku-redis/index.js' {
  declare module.exports: $Exports<'heroku-redis'>;
}
declare module 'heroku-redis/lib/shared.js' {
  declare module.exports: $Exports<'heroku-redis/lib/shared'>;
}
