// flow-typed signature: fd227cf490e5dc18b9009f74fd248ca9
// flow-typed version: <<STUB>>/heroku-spaces_v2.9.5/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-spaces'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-spaces' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-spaces/commands/create' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/destroy' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/drains/get' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/drains/set' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/index' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/info' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/outbound-rules/add' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/outbound-rules/index' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/outbound-rules/remove' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/peering/accept' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/peering/destroy' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/peering/index' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/peering/info' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/ps' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/rename' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/topology' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/trusted-ips/add' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/trusted-ips/index' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/trusted-ips/remove' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/vpn/config' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/vpn/create' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/vpn/destroy' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/vpn/info' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/vpn/wait' {
  declare module.exports: any;
}

declare module 'heroku-spaces/commands/wait' {
  declare module.exports: any;
}

declare module 'heroku-spaces/lib/format' {
  declare module.exports: any;
}

declare module 'heroku-spaces/lib/log-drains' {
  declare module.exports: any;
}

declare module 'heroku-spaces/lib/outbound-rules' {
  declare module.exports: any;
}

declare module 'heroku-spaces/lib/parsers' {
  declare module.exports: any;
}

declare module 'heroku-spaces/lib/peering' {
  declare module.exports: any;
}

declare module 'heroku-spaces/lib/spaces' {
  declare module.exports: any;
}

declare module 'heroku-spaces/lib/trusted-ips' {
  declare module.exports: any;
}

declare module 'heroku-spaces/lib/vpn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-spaces/commands/create.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/create'>;
}
declare module 'heroku-spaces/commands/destroy.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/destroy'>;
}
declare module 'heroku-spaces/commands/drains/get.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/drains/get'>;
}
declare module 'heroku-spaces/commands/drains/set.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/drains/set'>;
}
declare module 'heroku-spaces/commands/index.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/index'>;
}
declare module 'heroku-spaces/commands/info.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/info'>;
}
declare module 'heroku-spaces/commands/outbound-rules/add.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/outbound-rules/add'>;
}
declare module 'heroku-spaces/commands/outbound-rules/index.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/outbound-rules/index'>;
}
declare module 'heroku-spaces/commands/outbound-rules/remove.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/outbound-rules/remove'>;
}
declare module 'heroku-spaces/commands/peering/accept.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/peering/accept'>;
}
declare module 'heroku-spaces/commands/peering/destroy.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/peering/destroy'>;
}
declare module 'heroku-spaces/commands/peering/index.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/peering/index'>;
}
declare module 'heroku-spaces/commands/peering/info.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/peering/info'>;
}
declare module 'heroku-spaces/commands/ps.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/ps'>;
}
declare module 'heroku-spaces/commands/rename.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/rename'>;
}
declare module 'heroku-spaces/commands/topology.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/topology'>;
}
declare module 'heroku-spaces/commands/trusted-ips/add.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/trusted-ips/add'>;
}
declare module 'heroku-spaces/commands/trusted-ips/index.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/trusted-ips/index'>;
}
declare module 'heroku-spaces/commands/trusted-ips/remove.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/trusted-ips/remove'>;
}
declare module 'heroku-spaces/commands/vpn/config.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/vpn/config'>;
}
declare module 'heroku-spaces/commands/vpn/create.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/vpn/create'>;
}
declare module 'heroku-spaces/commands/vpn/destroy.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/vpn/destroy'>;
}
declare module 'heroku-spaces/commands/vpn/info.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/vpn/info'>;
}
declare module 'heroku-spaces/commands/vpn/wait.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/vpn/wait'>;
}
declare module 'heroku-spaces/commands/wait.js' {
  declare module.exports: $Exports<'heroku-spaces/commands/wait'>;
}
declare module 'heroku-spaces/index' {
  declare module.exports: $Exports<'heroku-spaces'>;
}
declare module 'heroku-spaces/index.js' {
  declare module.exports: $Exports<'heroku-spaces'>;
}
declare module 'heroku-spaces/lib/format.js' {
  declare module.exports: $Exports<'heroku-spaces/lib/format'>;
}
declare module 'heroku-spaces/lib/log-drains.js' {
  declare module.exports: $Exports<'heroku-spaces/lib/log-drains'>;
}
declare module 'heroku-spaces/lib/outbound-rules.js' {
  declare module.exports: $Exports<'heroku-spaces/lib/outbound-rules'>;
}
declare module 'heroku-spaces/lib/parsers.js' {
  declare module.exports: $Exports<'heroku-spaces/lib/parsers'>;
}
declare module 'heroku-spaces/lib/peering.js' {
  declare module.exports: $Exports<'heroku-spaces/lib/peering'>;
}
declare module 'heroku-spaces/lib/spaces.js' {
  declare module.exports: $Exports<'heroku-spaces/lib/spaces'>;
}
declare module 'heroku-spaces/lib/trusted-ips.js' {
  declare module.exports: $Exports<'heroku-spaces/lib/trusted-ips'>;
}
declare module 'heroku-spaces/lib/vpn.js' {
  declare module.exports: $Exports<'heroku-spaces/lib/vpn'>;
}
