// flow-typed signature: 1349cd6fcea7ae47cd1b55910421d840
// flow-typed version: <<STUB>>/heroku-cli-addons_v1.2.25/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-cli-addons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-cli-addons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-cli-addons/commands/addons/attach' {
  declare module.exports: any;
}

declare module 'heroku-cli-addons/commands/addons/create' {
  declare module.exports: any;
}

declare module 'heroku-cli-addons/commands/addons/destroy' {
  declare module.exports: any;
}

declare module 'heroku-cli-addons/commands/addons/detach' {
  declare module.exports: any;
}

declare module 'heroku-cli-addons/commands/addons/docs' {
  declare module.exports: any;
}

declare module 'heroku-cli-addons/commands/addons/index' {
  declare module.exports: any;
}

declare module 'heroku-cli-addons/commands/addons/info' {
  declare module.exports: any;
}

declare module 'heroku-cli-addons/commands/addons/open' {
  declare module.exports: any;
}

declare module 'heroku-cli-addons/commands/addons/plans' {
  declare module.exports: any;
}

declare module 'heroku-cli-addons/commands/addons/rename' {
  declare module.exports: any;
}

declare module 'heroku-cli-addons/commands/addons/services' {
  declare module.exports: any;
}

declare module 'heroku-cli-addons/commands/addons/upgrade' {
  declare module.exports: any;
}

declare module 'heroku-cli-addons/commands/addons/wait' {
  declare module.exports: any;
}

declare module 'heroku-cli-addons/lib/addons_wait' {
  declare module.exports: any;
}

declare module 'heroku-cli-addons/lib/create_addon' {
  declare module.exports: any;
}

declare module 'heroku-cli-addons/lib/resolve' {
  declare module.exports: any;
}

declare module 'heroku-cli-addons/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-cli-addons/commands/addons/attach.js' {
  declare module.exports: $Exports<'heroku-cli-addons/commands/addons/attach'>;
}
declare module 'heroku-cli-addons/commands/addons/create.js' {
  declare module.exports: $Exports<'heroku-cli-addons/commands/addons/create'>;
}
declare module 'heroku-cli-addons/commands/addons/destroy.js' {
  declare module.exports: $Exports<'heroku-cli-addons/commands/addons/destroy'>;
}
declare module 'heroku-cli-addons/commands/addons/detach.js' {
  declare module.exports: $Exports<'heroku-cli-addons/commands/addons/detach'>;
}
declare module 'heroku-cli-addons/commands/addons/docs.js' {
  declare module.exports: $Exports<'heroku-cli-addons/commands/addons/docs'>;
}
declare module 'heroku-cli-addons/commands/addons/index.js' {
  declare module.exports: $Exports<'heroku-cli-addons/commands/addons/index'>;
}
declare module 'heroku-cli-addons/commands/addons/info.js' {
  declare module.exports: $Exports<'heroku-cli-addons/commands/addons/info'>;
}
declare module 'heroku-cli-addons/commands/addons/open.js' {
  declare module.exports: $Exports<'heroku-cli-addons/commands/addons/open'>;
}
declare module 'heroku-cli-addons/commands/addons/plans.js' {
  declare module.exports: $Exports<'heroku-cli-addons/commands/addons/plans'>;
}
declare module 'heroku-cli-addons/commands/addons/rename.js' {
  declare module.exports: $Exports<'heroku-cli-addons/commands/addons/rename'>;
}
declare module 'heroku-cli-addons/commands/addons/services.js' {
  declare module.exports: $Exports<'heroku-cli-addons/commands/addons/services'>;
}
declare module 'heroku-cli-addons/commands/addons/upgrade.js' {
  declare module.exports: $Exports<'heroku-cli-addons/commands/addons/upgrade'>;
}
declare module 'heroku-cli-addons/commands/addons/wait.js' {
  declare module.exports: $Exports<'heroku-cli-addons/commands/addons/wait'>;
}
declare module 'heroku-cli-addons/index' {
  declare module.exports: $Exports<'heroku-cli-addons'>;
}
declare module 'heroku-cli-addons/index.js' {
  declare module.exports: $Exports<'heroku-cli-addons'>;
}
declare module 'heroku-cli-addons/lib/addons_wait.js' {
  declare module.exports: $Exports<'heroku-cli-addons/lib/addons_wait'>;
}
declare module 'heroku-cli-addons/lib/create_addon.js' {
  declare module.exports: $Exports<'heroku-cli-addons/lib/create_addon'>;
}
declare module 'heroku-cli-addons/lib/resolve.js' {
  declare module.exports: $Exports<'heroku-cli-addons/lib/resolve'>;
}
declare module 'heroku-cli-addons/lib/util.js' {
  declare module.exports: $Exports<'heroku-cli-addons/lib/util'>;
}
