// flow-typed signature: dc78ff58b9a3dff5889c5bbb6e22eb94
// flow-typed version: <<STUB>>/heroku-local_v5.1.21/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-local'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-local' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-local/commands/run' {
  declare module.exports: any;
}

declare module 'heroku-local/commands/start' {
  declare module.exports: any;
}

declare module 'heroku-local/commands/version' {
  declare module.exports: any;
}

declare module 'heroku-local/lib/fork_foreman' {
  declare module.exports: any;
}

declare module 'heroku-local/lib/run_foreman' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-local/commands/run.js' {
  declare module.exports: $Exports<'heroku-local/commands/run'>;
}
declare module 'heroku-local/commands/start.js' {
  declare module.exports: $Exports<'heroku-local/commands/start'>;
}
declare module 'heroku-local/commands/version.js' {
  declare module.exports: $Exports<'heroku-local/commands/version'>;
}
declare module 'heroku-local/index' {
  declare module.exports: $Exports<'heroku-local'>;
}
declare module 'heroku-local/index.js' {
  declare module.exports: $Exports<'heroku-local'>;
}
declare module 'heroku-local/lib/fork_foreman.js' {
  declare module.exports: $Exports<'heroku-local/lib/fork_foreman'>;
}
declare module 'heroku-local/lib/run_foreman.js' {
  declare module.exports: $Exports<'heroku-local/lib/run_foreman'>;
}
