// flow-typed signature: dd895585b633426c4da6af14cb26d448
// flow-typed version: <<STUB>>/heroku-pipelines_v2.1.3/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-pipelines'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-pipelines' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-pipelines/commands/pipelines/add' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/commands/pipelines/create' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/commands/pipelines/destroy' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/commands/pipelines/diff' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/commands/pipelines/index' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/commands/pipelines/info' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/commands/pipelines/open' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/commands/pipelines/promote' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/commands/pipelines/remove' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/commands/pipelines/rename' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/commands/pipelines/setup' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/commands/pipelines/update' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/lib/api' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/lib/disambiguate' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/lib/github-api' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/lib/infer' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/lib/key-by' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/lib/kolkrabbi-api' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/lib/prompt' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/lib/stages' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/test/commands/pipelines/add' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/test/commands/pipelines/create' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/test/commands/pipelines/destroy' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/test/commands/pipelines/diff' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/test/commands/pipelines/index' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/test/commands/pipelines/info' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/test/commands/pipelines/open' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/test/commands/pipelines/promote' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/test/commands/pipelines/remove' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/test/commands/pipelines/rename' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/test/commands/pipelines/setup' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/test/commands/pipelines/update' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/test/init' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/test/lib/infer' {
  declare module.exports: any;
}

declare module 'heroku-pipelines/test/lib/key-by' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-pipelines/commands/pipelines/add.js' {
  declare module.exports: $Exports<'heroku-pipelines/commands/pipelines/add'>;
}
declare module 'heroku-pipelines/commands/pipelines/create.js' {
  declare module.exports: $Exports<'heroku-pipelines/commands/pipelines/create'>;
}
declare module 'heroku-pipelines/commands/pipelines/destroy.js' {
  declare module.exports: $Exports<'heroku-pipelines/commands/pipelines/destroy'>;
}
declare module 'heroku-pipelines/commands/pipelines/diff.js' {
  declare module.exports: $Exports<'heroku-pipelines/commands/pipelines/diff'>;
}
declare module 'heroku-pipelines/commands/pipelines/index.js' {
  declare module.exports: $Exports<'heroku-pipelines/commands/pipelines/index'>;
}
declare module 'heroku-pipelines/commands/pipelines/info.js' {
  declare module.exports: $Exports<'heroku-pipelines/commands/pipelines/info'>;
}
declare module 'heroku-pipelines/commands/pipelines/open.js' {
  declare module.exports: $Exports<'heroku-pipelines/commands/pipelines/open'>;
}
declare module 'heroku-pipelines/commands/pipelines/promote.js' {
  declare module.exports: $Exports<'heroku-pipelines/commands/pipelines/promote'>;
}
declare module 'heroku-pipelines/commands/pipelines/remove.js' {
  declare module.exports: $Exports<'heroku-pipelines/commands/pipelines/remove'>;
}
declare module 'heroku-pipelines/commands/pipelines/rename.js' {
  declare module.exports: $Exports<'heroku-pipelines/commands/pipelines/rename'>;
}
declare module 'heroku-pipelines/commands/pipelines/setup.js' {
  declare module.exports: $Exports<'heroku-pipelines/commands/pipelines/setup'>;
}
declare module 'heroku-pipelines/commands/pipelines/update.js' {
  declare module.exports: $Exports<'heroku-pipelines/commands/pipelines/update'>;
}
declare module 'heroku-pipelines/index' {
  declare module.exports: $Exports<'heroku-pipelines'>;
}
declare module 'heroku-pipelines/index.js' {
  declare module.exports: $Exports<'heroku-pipelines'>;
}
declare module 'heroku-pipelines/lib/api.js' {
  declare module.exports: $Exports<'heroku-pipelines/lib/api'>;
}
declare module 'heroku-pipelines/lib/disambiguate.js' {
  declare module.exports: $Exports<'heroku-pipelines/lib/disambiguate'>;
}
declare module 'heroku-pipelines/lib/github-api.js' {
  declare module.exports: $Exports<'heroku-pipelines/lib/github-api'>;
}
declare module 'heroku-pipelines/lib/infer.js' {
  declare module.exports: $Exports<'heroku-pipelines/lib/infer'>;
}
declare module 'heroku-pipelines/lib/key-by.js' {
  declare module.exports: $Exports<'heroku-pipelines/lib/key-by'>;
}
declare module 'heroku-pipelines/lib/kolkrabbi-api.js' {
  declare module.exports: $Exports<'heroku-pipelines/lib/kolkrabbi-api'>;
}
declare module 'heroku-pipelines/lib/prompt.js' {
  declare module.exports: $Exports<'heroku-pipelines/lib/prompt'>;
}
declare module 'heroku-pipelines/lib/stages.js' {
  declare module.exports: $Exports<'heroku-pipelines/lib/stages'>;
}
declare module 'heroku-pipelines/test/commands/pipelines/add.js' {
  declare module.exports: $Exports<'heroku-pipelines/test/commands/pipelines/add'>;
}
declare module 'heroku-pipelines/test/commands/pipelines/create.js' {
  declare module.exports: $Exports<'heroku-pipelines/test/commands/pipelines/create'>;
}
declare module 'heroku-pipelines/test/commands/pipelines/destroy.js' {
  declare module.exports: $Exports<'heroku-pipelines/test/commands/pipelines/destroy'>;
}
declare module 'heroku-pipelines/test/commands/pipelines/diff.js' {
  declare module.exports: $Exports<'heroku-pipelines/test/commands/pipelines/diff'>;
}
declare module 'heroku-pipelines/test/commands/pipelines/index.js' {
  declare module.exports: $Exports<'heroku-pipelines/test/commands/pipelines/index'>;
}
declare module 'heroku-pipelines/test/commands/pipelines/info.js' {
  declare module.exports: $Exports<'heroku-pipelines/test/commands/pipelines/info'>;
}
declare module 'heroku-pipelines/test/commands/pipelines/open.js' {
  declare module.exports: $Exports<'heroku-pipelines/test/commands/pipelines/open'>;
}
declare module 'heroku-pipelines/test/commands/pipelines/promote.js' {
  declare module.exports: $Exports<'heroku-pipelines/test/commands/pipelines/promote'>;
}
declare module 'heroku-pipelines/test/commands/pipelines/remove.js' {
  declare module.exports: $Exports<'heroku-pipelines/test/commands/pipelines/remove'>;
}
declare module 'heroku-pipelines/test/commands/pipelines/rename.js' {
  declare module.exports: $Exports<'heroku-pipelines/test/commands/pipelines/rename'>;
}
declare module 'heroku-pipelines/test/commands/pipelines/setup.js' {
  declare module.exports: $Exports<'heroku-pipelines/test/commands/pipelines/setup'>;
}
declare module 'heroku-pipelines/test/commands/pipelines/update.js' {
  declare module.exports: $Exports<'heroku-pipelines/test/commands/pipelines/update'>;
}
declare module 'heroku-pipelines/test/init.js' {
  declare module.exports: $Exports<'heroku-pipelines/test/init'>;
}
declare module 'heroku-pipelines/test/lib/infer.js' {
  declare module.exports: $Exports<'heroku-pipelines/test/lib/infer'>;
}
declare module 'heroku-pipelines/test/lib/key-by.js' {
  declare module.exports: $Exports<'heroku-pipelines/test/lib/key-by'>;
}
