// flow-typed signature: 4f3b5cf3e3cad70cd2add8050f46c7e9
// flow-typed version: <<STUB>>/heroku-webhooks_v1.0.7/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-webhooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-webhooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-webhooks/commands/webhooks/add' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/commands/webhooks/deliveries/index' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/commands/webhooks/deliveries/info' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/commands/webhooks/events/index' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/commands/webhooks/events/info' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/commands/webhooks/index' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/commands/webhooks/info' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/commands/webhooks/remove' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/commands/webhooks/update' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/test/commands/webhooks/add' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/test/commands/webhooks/deliveries/index' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/test/commands/webhooks/deliveries/info' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/test/commands/webhooks/events/index' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/test/commands/webhooks/events/info' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/test/commands/webhooks/index' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/test/commands/webhooks/info' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/test/commands/webhooks/remove' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/test/commands/webhooks/update' {
  declare module.exports: any;
}

declare module 'heroku-webhooks/test/helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-webhooks/commands/webhooks/add.js' {
  declare module.exports: $Exports<'heroku-webhooks/commands/webhooks/add'>;
}
declare module 'heroku-webhooks/commands/webhooks/deliveries/index.js' {
  declare module.exports: $Exports<'heroku-webhooks/commands/webhooks/deliveries/index'>;
}
declare module 'heroku-webhooks/commands/webhooks/deliveries/info.js' {
  declare module.exports: $Exports<'heroku-webhooks/commands/webhooks/deliveries/info'>;
}
declare module 'heroku-webhooks/commands/webhooks/events/index.js' {
  declare module.exports: $Exports<'heroku-webhooks/commands/webhooks/events/index'>;
}
declare module 'heroku-webhooks/commands/webhooks/events/info.js' {
  declare module.exports: $Exports<'heroku-webhooks/commands/webhooks/events/info'>;
}
declare module 'heroku-webhooks/commands/webhooks/index.js' {
  declare module.exports: $Exports<'heroku-webhooks/commands/webhooks/index'>;
}
declare module 'heroku-webhooks/commands/webhooks/info.js' {
  declare module.exports: $Exports<'heroku-webhooks/commands/webhooks/info'>;
}
declare module 'heroku-webhooks/commands/webhooks/remove.js' {
  declare module.exports: $Exports<'heroku-webhooks/commands/webhooks/remove'>;
}
declare module 'heroku-webhooks/commands/webhooks/update.js' {
  declare module.exports: $Exports<'heroku-webhooks/commands/webhooks/update'>;
}
declare module 'heroku-webhooks/index' {
  declare module.exports: $Exports<'heroku-webhooks'>;
}
declare module 'heroku-webhooks/index.js' {
  declare module.exports: $Exports<'heroku-webhooks'>;
}
declare module 'heroku-webhooks/test/commands/webhooks/add.js' {
  declare module.exports: $Exports<'heroku-webhooks/test/commands/webhooks/add'>;
}
declare module 'heroku-webhooks/test/commands/webhooks/deliveries/index.js' {
  declare module.exports: $Exports<'heroku-webhooks/test/commands/webhooks/deliveries/index'>;
}
declare module 'heroku-webhooks/test/commands/webhooks/deliveries/info.js' {
  declare module.exports: $Exports<'heroku-webhooks/test/commands/webhooks/deliveries/info'>;
}
declare module 'heroku-webhooks/test/commands/webhooks/events/index.js' {
  declare module.exports: $Exports<'heroku-webhooks/test/commands/webhooks/events/index'>;
}
declare module 'heroku-webhooks/test/commands/webhooks/events/info.js' {
  declare module.exports: $Exports<'heroku-webhooks/test/commands/webhooks/events/info'>;
}
declare module 'heroku-webhooks/test/commands/webhooks/index.js' {
  declare module.exports: $Exports<'heroku-webhooks/test/commands/webhooks/index'>;
}
declare module 'heroku-webhooks/test/commands/webhooks/info.js' {
  declare module.exports: $Exports<'heroku-webhooks/test/commands/webhooks/info'>;
}
declare module 'heroku-webhooks/test/commands/webhooks/remove.js' {
  declare module.exports: $Exports<'heroku-webhooks/test/commands/webhooks/remove'>;
}
declare module 'heroku-webhooks/test/commands/webhooks/update.js' {
  declare module.exports: $Exports<'heroku-webhooks/test/commands/webhooks/update'>;
}
declare module 'heroku-webhooks/test/helpers.js' {
  declare module.exports: $Exports<'heroku-webhooks/test/helpers'>;
}
