// flow-typed signature: f219eea171fb015d6548713e67dc624b
// flow-typed version: <<STUB>>/heroku-orgs_v1.6.4/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-orgs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-orgs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-orgs/commands/access/add' {
  declare module.exports: any;
}

declare module 'heroku-orgs/commands/access/index' {
  declare module.exports: any;
}

declare module 'heroku-orgs/commands/access/remove' {
  declare module.exports: any;
}

declare module 'heroku-orgs/commands/access/update' {
  declare module.exports: any;
}

declare module 'heroku-orgs/commands/apps/join' {
  declare module.exports: any;
}

declare module 'heroku-orgs/commands/apps/leave' {
  declare module.exports: any;
}

declare module 'heroku-orgs/commands/apps/lock' {
  declare module.exports: any;
}

declare module 'heroku-orgs/commands/apps/transfer' {
  declare module.exports: any;
}

declare module 'heroku-orgs/commands/apps/unlock' {
  declare module.exports: any;
}

declare module 'heroku-orgs/commands/members/add' {
  declare module.exports: any;
}

declare module 'heroku-orgs/commands/members/index' {
  declare module.exports: any;
}

declare module 'heroku-orgs/commands/members/remove' {
  declare module.exports: any;
}

declare module 'heroku-orgs/commands/orgs/default' {
  declare module.exports: any;
}

declare module 'heroku-orgs/commands/orgs/index' {
  declare module.exports: any;
}

declare module 'heroku-orgs/commands/orgs/open' {
  declare module.exports: any;
}

declare module 'heroku-orgs/commands/teams/index' {
  declare module.exports: any;
}

declare module 'heroku-orgs/lib/app_transfer' {
  declare module.exports: any;
}

declare module 'heroku-orgs/lib/error' {
  declare module.exports: any;
}

declare module 'heroku-orgs/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-orgs/commands/access/add.js' {
  declare module.exports: $Exports<'heroku-orgs/commands/access/add'>;
}
declare module 'heroku-orgs/commands/access/index.js' {
  declare module.exports: $Exports<'heroku-orgs/commands/access/index'>;
}
declare module 'heroku-orgs/commands/access/remove.js' {
  declare module.exports: $Exports<'heroku-orgs/commands/access/remove'>;
}
declare module 'heroku-orgs/commands/access/update.js' {
  declare module.exports: $Exports<'heroku-orgs/commands/access/update'>;
}
declare module 'heroku-orgs/commands/apps/join.js' {
  declare module.exports: $Exports<'heroku-orgs/commands/apps/join'>;
}
declare module 'heroku-orgs/commands/apps/leave.js' {
  declare module.exports: $Exports<'heroku-orgs/commands/apps/leave'>;
}
declare module 'heroku-orgs/commands/apps/lock.js' {
  declare module.exports: $Exports<'heroku-orgs/commands/apps/lock'>;
}
declare module 'heroku-orgs/commands/apps/transfer.js' {
  declare module.exports: $Exports<'heroku-orgs/commands/apps/transfer'>;
}
declare module 'heroku-orgs/commands/apps/unlock.js' {
  declare module.exports: $Exports<'heroku-orgs/commands/apps/unlock'>;
}
declare module 'heroku-orgs/commands/members/add.js' {
  declare module.exports: $Exports<'heroku-orgs/commands/members/add'>;
}
declare module 'heroku-orgs/commands/members/index.js' {
  declare module.exports: $Exports<'heroku-orgs/commands/members/index'>;
}
declare module 'heroku-orgs/commands/members/remove.js' {
  declare module.exports: $Exports<'heroku-orgs/commands/members/remove'>;
}
declare module 'heroku-orgs/commands/orgs/default.js' {
  declare module.exports: $Exports<'heroku-orgs/commands/orgs/default'>;
}
declare module 'heroku-orgs/commands/orgs/index.js' {
  declare module.exports: $Exports<'heroku-orgs/commands/orgs/index'>;
}
declare module 'heroku-orgs/commands/orgs/open.js' {
  declare module.exports: $Exports<'heroku-orgs/commands/orgs/open'>;
}
declare module 'heroku-orgs/commands/teams/index.js' {
  declare module.exports: $Exports<'heroku-orgs/commands/teams/index'>;
}
declare module 'heroku-orgs/index' {
  declare module.exports: $Exports<'heroku-orgs'>;
}
declare module 'heroku-orgs/index.js' {
  declare module.exports: $Exports<'heroku-orgs'>;
}
declare module 'heroku-orgs/lib/app_transfer.js' {
  declare module.exports: $Exports<'heroku-orgs/lib/app_transfer'>;
}
declare module 'heroku-orgs/lib/error.js' {
  declare module.exports: $Exports<'heroku-orgs/lib/error'>;
}
declare module 'heroku-orgs/lib/utils.js' {
  declare module.exports: $Exports<'heroku-orgs/lib/utils'>;
}
