// flow-typed signature: 8f3a44d4a488772dd7a98e6ecab2f0bb
// flow-typed version: <<STUB>>/heroku-run_v3.5.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-run'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-run' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-run/commands/console' {
  declare module.exports: any;
}

declare module 'heroku-run/commands/detached' {
  declare module.exports: any;
}

declare module 'heroku-run/commands/inside' {
  declare module.exports: any;
}

declare module 'heroku-run/commands/logs' {
  declare module.exports: any;
}

declare module 'heroku-run/commands/rake' {
  declare module.exports: any;
}

declare module 'heroku-run/commands/run' {
  declare module.exports: any;
}

declare module 'heroku-run/lib/dyno' {
  declare module.exports: any;
}

declare module 'heroku-run/lib/helpers' {
  declare module.exports: any;
}

declare module 'heroku-run/lib/line_transform' {
  declare module.exports: any;
}

declare module 'heroku-run/lib/log_displayer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-run/commands/console.js' {
  declare module.exports: $Exports<'heroku-run/commands/console'>;
}
declare module 'heroku-run/commands/detached.js' {
  declare module.exports: $Exports<'heroku-run/commands/detached'>;
}
declare module 'heroku-run/commands/inside.js' {
  declare module.exports: $Exports<'heroku-run/commands/inside'>;
}
declare module 'heroku-run/commands/logs.js' {
  declare module.exports: $Exports<'heroku-run/commands/logs'>;
}
declare module 'heroku-run/commands/rake.js' {
  declare module.exports: $Exports<'heroku-run/commands/rake'>;
}
declare module 'heroku-run/commands/run.js' {
  declare module.exports: $Exports<'heroku-run/commands/run'>;
}
declare module 'heroku-run/index' {
  declare module.exports: $Exports<'heroku-run'>;
}
declare module 'heroku-run/index.js' {
  declare module.exports: $Exports<'heroku-run'>;
}
declare module 'heroku-run/lib/dyno.js' {
  declare module.exports: $Exports<'heroku-run/lib/dyno'>;
}
declare module 'heroku-run/lib/helpers.js' {
  declare module.exports: $Exports<'heroku-run/lib/helpers'>;
}
declare module 'heroku-run/lib/line_transform.js' {
  declare module.exports: $Exports<'heroku-run/lib/line_transform'>;
}
declare module 'heroku-run/lib/log_displayer.js' {
  declare module.exports: $Exports<'heroku-run/lib/log_displayer'>;
}
