// flow-typed signature: 2105ab366e1133048528463245f6be1c
// flow-typed version: <<STUB>>/heroku-certs_v1.1.41/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-certs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-certs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-certs/commands/certs/add' {
  declare module.exports: any;
}

declare module 'heroku-certs/commands/certs/auto' {
  declare module.exports: any;
}

declare module 'heroku-certs/commands/certs/auto/disable' {
  declare module.exports: any;
}

declare module 'heroku-certs/commands/certs/auto/enable' {
  declare module.exports: any;
}

declare module 'heroku-certs/commands/certs/auto/refresh' {
  declare module.exports: any;
}

declare module 'heroku-certs/commands/certs/chain' {
  declare module.exports: any;
}

declare module 'heroku-certs/commands/certs/generate' {
  declare module.exports: any;
}

declare module 'heroku-certs/commands/certs/index' {
  declare module.exports: any;
}

declare module 'heroku-certs/commands/certs/info' {
  declare module.exports: any;
}

declare module 'heroku-certs/commands/certs/key' {
  declare module.exports: any;
}

declare module 'heroku-certs/commands/certs/remove' {
  declare module.exports: any;
}

declare module 'heroku-certs/commands/certs/rollback' {
  declare module.exports: any;
}

declare module 'heroku-certs/commands/certs/update' {
  declare module.exports: any;
}

declare module 'heroku-certs/lib/certificate_details' {
  declare module.exports: any;
}

declare module 'heroku-certs/lib/display_table' {
  declare module.exports: any;
}

declare module 'heroku-certs/lib/display_warnings' {
  declare module.exports: any;
}

declare module 'heroku-certs/lib/domains' {
  declare module.exports: any;
}

declare module 'heroku-certs/lib/endpoints' {
  declare module.exports: any;
}

declare module 'heroku-certs/lib/error' {
  declare module.exports: any;
}

declare module 'heroku-certs/lib/find_match' {
  declare module.exports: any;
}

declare module 'heroku-certs/lib/flags' {
  declare module.exports: any;
}

declare module 'heroku-certs/lib/format_date' {
  declare module.exports: any;
}

declare module 'heroku-certs/lib/format_endpoint' {
  declare module.exports: any;
}

declare module 'heroku-certs/lib/get_cert_and_key' {
  declare module.exports: any;
}

declare module 'heroku-certs/lib/is_wildcard_match' {
  declare module.exports: any;
}

declare module 'heroku-certs/lib/is_wildcard' {
  declare module.exports: any;
}

declare module 'heroku-certs/lib/openssl' {
  declare module.exports: any;
}

declare module 'heroku-certs/lib/read_file' {
  declare module.exports: any;
}

declare module 'heroku-certs/lib/ssl_doctor' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/assert_exit' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/commands/certs/add' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/commands/certs/auto' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/commands/certs/auto/disable' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/commands/certs/auto/enable' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/commands/certs/auto/refresh' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/commands/certs/chain' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/commands/certs/generate' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/commands/certs/index' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/commands/certs/info' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/commands/certs/key' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/commands/certs/remove' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/commands/certs/rollback' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/commands/certs/shared_sni' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/commands/certs/shared_ssl' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/commands/certs/shared' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/commands/certs/update' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/helpers' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/stubs/sni-endpoints' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/stubs/ssl-endpoints' {
  declare module.exports: any;
}

declare module 'heroku-certs/test/unwrap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-certs/commands/certs/add.js' {
  declare module.exports: $Exports<'heroku-certs/commands/certs/add'>;
}
declare module 'heroku-certs/commands/certs/auto.js' {
  declare module.exports: $Exports<'heroku-certs/commands/certs/auto'>;
}
declare module 'heroku-certs/commands/certs/auto/disable.js' {
  declare module.exports: $Exports<'heroku-certs/commands/certs/auto/disable'>;
}
declare module 'heroku-certs/commands/certs/auto/enable.js' {
  declare module.exports: $Exports<'heroku-certs/commands/certs/auto/enable'>;
}
declare module 'heroku-certs/commands/certs/auto/refresh.js' {
  declare module.exports: $Exports<'heroku-certs/commands/certs/auto/refresh'>;
}
declare module 'heroku-certs/commands/certs/chain.js' {
  declare module.exports: $Exports<'heroku-certs/commands/certs/chain'>;
}
declare module 'heroku-certs/commands/certs/generate.js' {
  declare module.exports: $Exports<'heroku-certs/commands/certs/generate'>;
}
declare module 'heroku-certs/commands/certs/index.js' {
  declare module.exports: $Exports<'heroku-certs/commands/certs/index'>;
}
declare module 'heroku-certs/commands/certs/info.js' {
  declare module.exports: $Exports<'heroku-certs/commands/certs/info'>;
}
declare module 'heroku-certs/commands/certs/key.js' {
  declare module.exports: $Exports<'heroku-certs/commands/certs/key'>;
}
declare module 'heroku-certs/commands/certs/remove.js' {
  declare module.exports: $Exports<'heroku-certs/commands/certs/remove'>;
}
declare module 'heroku-certs/commands/certs/rollback.js' {
  declare module.exports: $Exports<'heroku-certs/commands/certs/rollback'>;
}
declare module 'heroku-certs/commands/certs/update.js' {
  declare module.exports: $Exports<'heroku-certs/commands/certs/update'>;
}
declare module 'heroku-certs/index' {
  declare module.exports: $Exports<'heroku-certs'>;
}
declare module 'heroku-certs/index.js' {
  declare module.exports: $Exports<'heroku-certs'>;
}
declare module 'heroku-certs/lib/certificate_details.js' {
  declare module.exports: $Exports<'heroku-certs/lib/certificate_details'>;
}
declare module 'heroku-certs/lib/display_table.js' {
  declare module.exports: $Exports<'heroku-certs/lib/display_table'>;
}
declare module 'heroku-certs/lib/display_warnings.js' {
  declare module.exports: $Exports<'heroku-certs/lib/display_warnings'>;
}
declare module 'heroku-certs/lib/domains.js' {
  declare module.exports: $Exports<'heroku-certs/lib/domains'>;
}
declare module 'heroku-certs/lib/endpoints.js' {
  declare module.exports: $Exports<'heroku-certs/lib/endpoints'>;
}
declare module 'heroku-certs/lib/error.js' {
  declare module.exports: $Exports<'heroku-certs/lib/error'>;
}
declare module 'heroku-certs/lib/find_match.js' {
  declare module.exports: $Exports<'heroku-certs/lib/find_match'>;
}
declare module 'heroku-certs/lib/flags.js' {
  declare module.exports: $Exports<'heroku-certs/lib/flags'>;
}
declare module 'heroku-certs/lib/format_date.js' {
  declare module.exports: $Exports<'heroku-certs/lib/format_date'>;
}
declare module 'heroku-certs/lib/format_endpoint.js' {
  declare module.exports: $Exports<'heroku-certs/lib/format_endpoint'>;
}
declare module 'heroku-certs/lib/get_cert_and_key.js' {
  declare module.exports: $Exports<'heroku-certs/lib/get_cert_and_key'>;
}
declare module 'heroku-certs/lib/is_wildcard_match.js' {
  declare module.exports: $Exports<'heroku-certs/lib/is_wildcard_match'>;
}
declare module 'heroku-certs/lib/is_wildcard.js' {
  declare module.exports: $Exports<'heroku-certs/lib/is_wildcard'>;
}
declare module 'heroku-certs/lib/openssl.js' {
  declare module.exports: $Exports<'heroku-certs/lib/openssl'>;
}
declare module 'heroku-certs/lib/read_file.js' {
  declare module.exports: $Exports<'heroku-certs/lib/read_file'>;
}
declare module 'heroku-certs/lib/ssl_doctor.js' {
  declare module.exports: $Exports<'heroku-certs/lib/ssl_doctor'>;
}
declare module 'heroku-certs/test/assert_exit.js' {
  declare module.exports: $Exports<'heroku-certs/test/assert_exit'>;
}
declare module 'heroku-certs/test/commands/certs/add.js' {
  declare module.exports: $Exports<'heroku-certs/test/commands/certs/add'>;
}
declare module 'heroku-certs/test/commands/certs/auto.js' {
  declare module.exports: $Exports<'heroku-certs/test/commands/certs/auto'>;
}
declare module 'heroku-certs/test/commands/certs/auto/disable.js' {
  declare module.exports: $Exports<'heroku-certs/test/commands/certs/auto/disable'>;
}
declare module 'heroku-certs/test/commands/certs/auto/enable.js' {
  declare module.exports: $Exports<'heroku-certs/test/commands/certs/auto/enable'>;
}
declare module 'heroku-certs/test/commands/certs/auto/refresh.js' {
  declare module.exports: $Exports<'heroku-certs/test/commands/certs/auto/refresh'>;
}
declare module 'heroku-certs/test/commands/certs/chain.js' {
  declare module.exports: $Exports<'heroku-certs/test/commands/certs/chain'>;
}
declare module 'heroku-certs/test/commands/certs/generate.js' {
  declare module.exports: $Exports<'heroku-certs/test/commands/certs/generate'>;
}
declare module 'heroku-certs/test/commands/certs/index.js' {
  declare module.exports: $Exports<'heroku-certs/test/commands/certs/index'>;
}
declare module 'heroku-certs/test/commands/certs/info.js' {
  declare module.exports: $Exports<'heroku-certs/test/commands/certs/info'>;
}
declare module 'heroku-certs/test/commands/certs/key.js' {
  declare module.exports: $Exports<'heroku-certs/test/commands/certs/key'>;
}
declare module 'heroku-certs/test/commands/certs/remove.js' {
  declare module.exports: $Exports<'heroku-certs/test/commands/certs/remove'>;
}
declare module 'heroku-certs/test/commands/certs/rollback.js' {
  declare module.exports: $Exports<'heroku-certs/test/commands/certs/rollback'>;
}
declare module 'heroku-certs/test/commands/certs/shared_sni.js' {
  declare module.exports: $Exports<'heroku-certs/test/commands/certs/shared_sni'>;
}
declare module 'heroku-certs/test/commands/certs/shared_ssl.js' {
  declare module.exports: $Exports<'heroku-certs/test/commands/certs/shared_ssl'>;
}
declare module 'heroku-certs/test/commands/certs/shared.js' {
  declare module.exports: $Exports<'heroku-certs/test/commands/certs/shared'>;
}
declare module 'heroku-certs/test/commands/certs/update.js' {
  declare module.exports: $Exports<'heroku-certs/test/commands/certs/update'>;
}
declare module 'heroku-certs/test/helpers.js' {
  declare module.exports: $Exports<'heroku-certs/test/helpers'>;
}
declare module 'heroku-certs/test/stubs/sni-endpoints.js' {
  declare module.exports: $Exports<'heroku-certs/test/stubs/sni-endpoints'>;
}
declare module 'heroku-certs/test/stubs/ssl-endpoints.js' {
  declare module.exports: $Exports<'heroku-certs/test/stubs/ssl-endpoints'>;
}
declare module 'heroku-certs/test/unwrap.js' {
  declare module.exports: $Exports<'heroku-certs/test/unwrap'>;
}
