// flow-typed signature: 327c6859ff902dacf136393fba2b4a9f
// flow-typed version: <<STUB>>/heroku-pg_v2.3.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-pg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-pg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-pg/commands/backups/cancel' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/backups/capture' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/backups/delete' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/backups/download' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/backups/index' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/backups/info' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/backups/restore' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/backups/schedule' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/backups/schedules' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/backups/unschedule' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/backups/url' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/copy' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/credentials' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/credentials/create' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/credentials/destroy' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/credentials/repair_default' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/credentials/rotate' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/credentials/url' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/diagnose' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/info' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/kill' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/killall' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/links/create' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/links/destroy' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/links/index' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/maintenance/index' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/maintenance/run' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/maintenance/window' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/promote' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/ps' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/psql' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/pull' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/reset' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/settings/index' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/settings/log_lock_waits' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/settings/log_min_duration_statement' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/settings/log_statement' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/unfollow' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/upgrade' {
  declare module.exports: any;
}

declare module 'heroku-pg/commands/wait' {
  declare module.exports: any;
}

declare module 'heroku-pg/lib/bastion' {
  declare module.exports: any;
}

declare module 'heroku-pg/lib/config' {
  declare module.exports: any;
}

declare module 'heroku-pg/lib/debug' {
  declare module.exports: any;
}

declare module 'heroku-pg/lib/download' {
  declare module.exports: any;
}

declare module 'heroku-pg/lib/fetcher' {
  declare module.exports: any;
}

declare module 'heroku-pg/lib/host' {
  declare module.exports: any;
}

declare module 'heroku-pg/lib/memoize_promise' {
  declare module.exports: any;
}

declare module 'heroku-pg/lib/pgbackups' {
  declare module.exports: any;
}

declare module 'heroku-pg/lib/psql' {
  declare module.exports: any;
}

declare module 'heroku-pg/lib/setter' {
  declare module.exports: any;
}

declare module 'heroku-pg/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-pg/commands/backups/cancel.js' {
  declare module.exports: $Exports<'heroku-pg/commands/backups/cancel'>;
}
declare module 'heroku-pg/commands/backups/capture.js' {
  declare module.exports: $Exports<'heroku-pg/commands/backups/capture'>;
}
declare module 'heroku-pg/commands/backups/delete.js' {
  declare module.exports: $Exports<'heroku-pg/commands/backups/delete'>;
}
declare module 'heroku-pg/commands/backups/download.js' {
  declare module.exports: $Exports<'heroku-pg/commands/backups/download'>;
}
declare module 'heroku-pg/commands/backups/index.js' {
  declare module.exports: $Exports<'heroku-pg/commands/backups/index'>;
}
declare module 'heroku-pg/commands/backups/info.js' {
  declare module.exports: $Exports<'heroku-pg/commands/backups/info'>;
}
declare module 'heroku-pg/commands/backups/restore.js' {
  declare module.exports: $Exports<'heroku-pg/commands/backups/restore'>;
}
declare module 'heroku-pg/commands/backups/schedule.js' {
  declare module.exports: $Exports<'heroku-pg/commands/backups/schedule'>;
}
declare module 'heroku-pg/commands/backups/schedules.js' {
  declare module.exports: $Exports<'heroku-pg/commands/backups/schedules'>;
}
declare module 'heroku-pg/commands/backups/unschedule.js' {
  declare module.exports: $Exports<'heroku-pg/commands/backups/unschedule'>;
}
declare module 'heroku-pg/commands/backups/url.js' {
  declare module.exports: $Exports<'heroku-pg/commands/backups/url'>;
}
declare module 'heroku-pg/commands/copy.js' {
  declare module.exports: $Exports<'heroku-pg/commands/copy'>;
}
declare module 'heroku-pg/commands/credentials.js' {
  declare module.exports: $Exports<'heroku-pg/commands/credentials'>;
}
declare module 'heroku-pg/commands/credentials/create.js' {
  declare module.exports: $Exports<'heroku-pg/commands/credentials/create'>;
}
declare module 'heroku-pg/commands/credentials/destroy.js' {
  declare module.exports: $Exports<'heroku-pg/commands/credentials/destroy'>;
}
declare module 'heroku-pg/commands/credentials/repair_default.js' {
  declare module.exports: $Exports<'heroku-pg/commands/credentials/repair_default'>;
}
declare module 'heroku-pg/commands/credentials/rotate.js' {
  declare module.exports: $Exports<'heroku-pg/commands/credentials/rotate'>;
}
declare module 'heroku-pg/commands/credentials/url.js' {
  declare module.exports: $Exports<'heroku-pg/commands/credentials/url'>;
}
declare module 'heroku-pg/commands/diagnose.js' {
  declare module.exports: $Exports<'heroku-pg/commands/diagnose'>;
}
declare module 'heroku-pg/commands/info.js' {
  declare module.exports: $Exports<'heroku-pg/commands/info'>;
}
declare module 'heroku-pg/commands/kill.js' {
  declare module.exports: $Exports<'heroku-pg/commands/kill'>;
}
declare module 'heroku-pg/commands/killall.js' {
  declare module.exports: $Exports<'heroku-pg/commands/killall'>;
}
declare module 'heroku-pg/commands/links/create.js' {
  declare module.exports: $Exports<'heroku-pg/commands/links/create'>;
}
declare module 'heroku-pg/commands/links/destroy.js' {
  declare module.exports: $Exports<'heroku-pg/commands/links/destroy'>;
}
declare module 'heroku-pg/commands/links/index.js' {
  declare module.exports: $Exports<'heroku-pg/commands/links/index'>;
}
declare module 'heroku-pg/commands/maintenance/index.js' {
  declare module.exports: $Exports<'heroku-pg/commands/maintenance/index'>;
}
declare module 'heroku-pg/commands/maintenance/run.js' {
  declare module.exports: $Exports<'heroku-pg/commands/maintenance/run'>;
}
declare module 'heroku-pg/commands/maintenance/window.js' {
  declare module.exports: $Exports<'heroku-pg/commands/maintenance/window'>;
}
declare module 'heroku-pg/commands/promote.js' {
  declare module.exports: $Exports<'heroku-pg/commands/promote'>;
}
declare module 'heroku-pg/commands/ps.js' {
  declare module.exports: $Exports<'heroku-pg/commands/ps'>;
}
declare module 'heroku-pg/commands/psql.js' {
  declare module.exports: $Exports<'heroku-pg/commands/psql'>;
}
declare module 'heroku-pg/commands/pull.js' {
  declare module.exports: $Exports<'heroku-pg/commands/pull'>;
}
declare module 'heroku-pg/commands/reset.js' {
  declare module.exports: $Exports<'heroku-pg/commands/reset'>;
}
declare module 'heroku-pg/commands/settings/index.js' {
  declare module.exports: $Exports<'heroku-pg/commands/settings/index'>;
}
declare module 'heroku-pg/commands/settings/log_lock_waits.js' {
  declare module.exports: $Exports<'heroku-pg/commands/settings/log_lock_waits'>;
}
declare module 'heroku-pg/commands/settings/log_min_duration_statement.js' {
  declare module.exports: $Exports<'heroku-pg/commands/settings/log_min_duration_statement'>;
}
declare module 'heroku-pg/commands/settings/log_statement.js' {
  declare module.exports: $Exports<'heroku-pg/commands/settings/log_statement'>;
}
declare module 'heroku-pg/commands/unfollow.js' {
  declare module.exports: $Exports<'heroku-pg/commands/unfollow'>;
}
declare module 'heroku-pg/commands/upgrade.js' {
  declare module.exports: $Exports<'heroku-pg/commands/upgrade'>;
}
declare module 'heroku-pg/commands/wait.js' {
  declare module.exports: $Exports<'heroku-pg/commands/wait'>;
}
declare module 'heroku-pg/index' {
  declare module.exports: $Exports<'heroku-pg'>;
}
declare module 'heroku-pg/index.js' {
  declare module.exports: $Exports<'heroku-pg'>;
}
declare module 'heroku-pg/lib/bastion.js' {
  declare module.exports: $Exports<'heroku-pg/lib/bastion'>;
}
declare module 'heroku-pg/lib/config.js' {
  declare module.exports: $Exports<'heroku-pg/lib/config'>;
}
declare module 'heroku-pg/lib/debug.js' {
  declare module.exports: $Exports<'heroku-pg/lib/debug'>;
}
declare module 'heroku-pg/lib/download.js' {
  declare module.exports: $Exports<'heroku-pg/lib/download'>;
}
declare module 'heroku-pg/lib/fetcher.js' {
  declare module.exports: $Exports<'heroku-pg/lib/fetcher'>;
}
declare module 'heroku-pg/lib/host.js' {
  declare module.exports: $Exports<'heroku-pg/lib/host'>;
}
declare module 'heroku-pg/lib/memoize_promise.js' {
  declare module.exports: $Exports<'heroku-pg/lib/memoize_promise'>;
}
declare module 'heroku-pg/lib/pgbackups.js' {
  declare module.exports: $Exports<'heroku-pg/lib/pgbackups'>;
}
declare module 'heroku-pg/lib/psql.js' {
  declare module.exports: $Exports<'heroku-pg/lib/psql'>;
}
declare module 'heroku-pg/lib/setter.js' {
  declare module.exports: $Exports<'heroku-pg/lib/setter'>;
}
declare module 'heroku-pg/lib/util.js' {
  declare module.exports: $Exports<'heroku-pg/lib/util'>;
}
