// flow-typed signature: d2aea48fbbd9a309155d766cd02ebf69
// flow-typed version: <<STUB>>/heroku-container-registry_v4.4.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'heroku-container-registry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'heroku-container-registry' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'heroku-container-registry/commands/index' {
  declare module.exports: any;
}

declare module 'heroku-container-registry/commands/login' {
  declare module.exports: any;
}

declare module 'heroku-container-registry/commands/logout' {
  declare module.exports: any;
}

declare module 'heroku-container-registry/commands/push' {
  declare module.exports: any;
}

declare module 'heroku-container-registry/commands/rm' {
  declare module.exports: any;
}

declare module 'heroku-container-registry/lib/log' {
  declare module.exports: any;
}

declare module 'heroku-container-registry/lib/sanbashi' {
  declare module.exports: any;
}

declare module 'heroku-container-registry/test/sanbashi.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'heroku-container-registry/commands/index.js' {
  declare module.exports: $Exports<'heroku-container-registry/commands/index'>;
}
declare module 'heroku-container-registry/commands/login.js' {
  declare module.exports: $Exports<'heroku-container-registry/commands/login'>;
}
declare module 'heroku-container-registry/commands/logout.js' {
  declare module.exports: $Exports<'heroku-container-registry/commands/logout'>;
}
declare module 'heroku-container-registry/commands/push.js' {
  declare module.exports: $Exports<'heroku-container-registry/commands/push'>;
}
declare module 'heroku-container-registry/commands/rm.js' {
  declare module.exports: $Exports<'heroku-container-registry/commands/rm'>;
}
declare module 'heroku-container-registry/index' {
  declare module.exports: $Exports<'heroku-container-registry'>;
}
declare module 'heroku-container-registry/index.js' {
  declare module.exports: $Exports<'heroku-container-registry'>;
}
declare module 'heroku-container-registry/lib/log.js' {
  declare module.exports: $Exports<'heroku-container-registry/lib/log'>;
}
declare module 'heroku-container-registry/lib/sanbashi.js' {
  declare module.exports: $Exports<'heroku-container-registry/lib/sanbashi'>;
}
declare module 'heroku-container-registry/test/sanbashi.test.js' {
  declare module.exports: $Exports<'heroku-container-registry/test/sanbashi.test'>;
}
