name: get version and channel
description: read package.json and return the full version and version-suffix/channel (ex 'beta' if x.y.z-beta.0)

inputs:
  path:
    description: path to the package.json
    required: false
    default: "package.json"

outputs:
  channel:
    description: version channel (ex 'beta' if 1.2.3-beta.0 ), if exists in package.json
  version:
    description: full version from package.json

runs:
  using: 'node16'
  main: 'dist/index.js'
