#!/usr/bin/env node

const execa = require('execa')
const path = require('path')

const root = path.join(__dirname, '..', '..')
const CLI_ROOT = path.join(root, 'packages', 'cli')

async function main() {
  await require('../utils/_update_channel')()
  await execa('ls', ['./node_modules'], {
    cwd: CLI_ROOT,
    stdio: 'inherit'
  })
  await execa('./node_modules/@rasphilco/dev-cli/bin/run', ['pack:deb'], {
    cwd: CLI_ROOT,
    stdio: 'inherit'
  })
}

main()
