#!/usr/bin/env node

const execa = require('execa')
const path = require('path')

const root = path.join(__dirname, '..', '..')
const CLI_ROOT = path.join(root, 'packages', 'cli')

async function main() {
  await require('../utils/_update_channel')()
  await execa('./node_modules/.bin/oclif', ['pack deb'], {
    cwd: CLI_ROOT,
    stdio: 'inherit'
  })
}

main()
