#!/bin/bash

set -e

if [ "$#" -ne 2 ]; then
  echo "USAGE: $0 SHA CHANNEL" 1>&2
  exit 1
fi

git fetch
git checkout $1
gpg --passphrase $HEROKU_WINDOWS_SIGNING_PASS -d resources/deb/key.gpg | gpg --import
CHANNEL=$2 make release -j ${JOBS:=6}
