#!/usr/bin/env bash

echo "stable"
# if [[ "${CHANNEL:-}" != "" ]]; then
#   echo "${CHANNEL}"
# elif [[ "${CIRCLE_TAG:-}" != "" ]]; then
#   echo "stable"
# elif [[ "${CIRCLE_BRANCH:-}" == "master" ]]; then
#   echo "beta"
# else
#   echo "dev"
# fi
