// flow-typed signature: 6a7627e2a7dc97e999ee33f44e5c4bcc
// flow-typed version: <<STUB>>/@heroku/heroku-cli-dev-center-generator_v1.1.5/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@heroku/heroku-cli-dev-center-generator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@heroku/heroku-cli-dev-center-generator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@heroku/heroku-cli-dev-center-generator/run' {
  declare module.exports: any;
}

declare module '@heroku/heroku-cli-dev-center-generator/src/setsumeisho' {
  declare module.exports: any;
}

// Filename aliases
declare module '@heroku/heroku-cli-dev-center-generator/run.js' {
  declare module.exports: $Exports<'@heroku/heroku-cli-dev-center-generator/run'>;
}
declare module '@heroku/heroku-cli-dev-center-generator/src/setsumeisho.js' {
  declare module.exports: $Exports<'@heroku/heroku-cli-dev-center-generator/src/setsumeisho'>;
}
