#!/usr/bin/env node

import qq from 'qqjs'
import getHerokuS3Bucket from '../utils/getHerokuS3Bucket.js'

qq.config.silent = false
qq.run(async () => {
  await qq.x('./node_modules/.bin/oclif upload:deb')
  const HEROKU_S3_BUCKET = await getHerokuS3Bucket()

  await qq.x(`aws s3 cp --content-type text/plain --cache-control "max-age: 604800" /home/runner/work/cli/cli/dist/apt/release.key "s3://${HEROKU_S3_BUCKET}/channels/stable/apt/release.key"`)
})
