#!/usr/bin/env node

import getHerokuS3Bucket from '../utils/get-heroku-s3-bucket.js'
import {run, shell, x} from '../utils/script-exec.js'

await run(async () => {
  await x('./node_modules/.bin/oclif', ['upload:deb'])
  const HEROKU_S3_BUCKET = await getHerokuS3Bucket()

  await shell(`aws s3 cp --content-type text/plain --cache-control "max-age: 604800" /home/runner/work/cli/cli/dist/apt/release.key "s3://${HEROKU_S3_BUCKET}/channels/stable/apt/release.key"`)
})
