#!/usr/bin/env bash

OS=darwin
ARCH=x64

source ./scripts/main

if [ $# -ne 1 ]; then
  echo "USAGE: $0 OUTPUT_DIR"
  exit 1
fi

"${root}/scripts/build_base" tmp/heroku

output="$(mkdir -p "$1" && cd "$1" && pwd)"

pkgbuild --root tmp/heroku \
  --identifier com.heroku.cli \
  --install-location /usr/local/lib/heroku \
  --version "$(version)" \
  --sign "Developer ID Installer: Heroku INC" \
  --scripts "${root}/scripts/darwin/scripts" \
  "${output}/heroku.pkg"
