#!/usr/bin/env bash

set -x

export OS=darwin
export ARCH=x64

source ./scripts/_init

"${scripts}/build/_workspace"

keychain=""

if [[ ! -z "${OSX_KEYCHAIN:-}" ]]; then
  keychain="--keychain ${OSX_KEYCHAIN}"
fi

# shellcheck disable=SC2086
pkgbuild --root "tmp/builds/${BASE}" \
  --identifier com.heroku.cli \
  --install-location /usr/local/lib/heroku \
  --version "${VERSION}" \
  --sign "Developer ID Installer: Heroku INC" \
  --scripts "${root}/scripts/darwin/scripts" \
  $keychain \
  "tmp/heroku-cli.pkg"
