#!/usr/bin/env bash

set -x

export OS=darwin
export ARCH=x64

source ./scripts/_init

script "build/base"
script "build/workspace"

keychain=""

if [[ ! -z "${OSX_KEYCHAIN:-}" ]]; then
  keychain="--keychain ${OSX_KEYCHAIN}"
fi

# shellcheck disable=SC2086
pkgbuild --root "$WORKSPACE_DIR" \
  --identifier com.heroku.cli \
  --install-location /usr/local/lib/heroku \
  --version "${VERSION}" \
  --sign "Developer ID Installer: Heroku INC" \
  --scripts "$ROOT_DIR/scripts/darwin/scripts" \
  $keychain \
  "tmp/heroku-cli.pkg"
