#!/bin/bash

source ./scripts/main

if [ $# -ne 1 ]; then
  echo "USAGE: $0 CHANNEL"
  exit 1
fi

"${__root}/scripts/build_base" darwin-x64 "$1" dist/darwin

mkdir -p dist

pkgbuild --root dist/darwin \
  --identifier com.heroku.cli \
  --install-location /usr/local/lib/heroku \
  --version "${__version}" \
  --sign "Developer ID Installer: Heroku INC" \
  --scripts "${__root}/scripts/macos/scripts" \
  dist/heroku.pkg
