#!/usr/bin/env bash

source ./scripts/main

if [ $# -ne 1 ]; then
  echo "USAGE: $0 CHANNEL"
  exit 1
fi

"${root}/scripts/build_base" darwin-x64 "$1" dist/darwin

mkdir -p dist

pkgbuild --root dist/darwin \
  --identifier com.heroku.cli \
  --install-location /usr/local/lib/heroku \
  --version "$(version)" \
  --sign "Developer ID Installer: Heroku INC" \
  --scripts "${root}/scripts/darwin/scripts" \
  dist/heroku.pkg
