#!/bin/bash

set -ex

ROOT=`pwd`

VERSION=`$ROOT/node_modules/cli-engine/bin/version`
NAME=`node -p "require('./package.json').name"`

mkdir -p $ROOT/tmp/tarballs
touch $ROOT/tmp/tarballs/.keep

ARCHS=(x86 x64)
for ARCH in "${ARCHS[@]}"; do
  TARBALL_BASE=$NAME-v$VERSION-windows-$ARCH.tar.gz
  WORKSPACE=$ROOT/tmp/build/$TARBALL_BASE

  if [ -e $WORKSPACE ]; then
    cp $WORKSPACE tmp/tarballs/windows-$ARCH.tar.gz
  fi
done

find $ROOT/tmp/tarballs
