#!/bin/bash

if [ $# -ne 1 ]; then
  echo "USAGE: $0 ARCH"
  exit 1
fi

ARCH=$1

set -ex

ROOT=`pwd`

VERSION=`$ROOT/node_modules/cli-engine/bin/version`
NAME=`node -p "require('./package.json').name"`

# setup workspace
TARBALL_BASE=windows-$ARCH.tar.gz
WORKSPACE=$ROOT/tmp/tarballs/$TARBALL_BASE

mkdir -p $ROOT/tmp/build

if [ -e $WORKSPACE ]; then
  cd $ROOT/tmp/build
  tar xfz $WORKSPACE
  cd $ROOT
fi
