#!/usr/bin/env bash

# shellcheck disable=SC2034

# fail wait when any children fails
set -m

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

# Set magic variables for current file & dir
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$(dirname "${dir}")" && pwd)"

function go_home () {
  cd "${root}"
}
go_home

function bg () {
  "$@" &
  pids="${pids:-} $!"
}

function wait_all () {
  for pid in $pids; do
    wait "${pid}" || exit 1
  done
}

function s3upload () {
  aws s3 cp "$@"
}
function s3uploadDayCache () {
  s3upload --cache-control max-age=86400 "$@"
}
function s3uploadHourCache () {
  s3upload --cache-control max-age=3600 "$@"
}
