#!/usr/bin/env bash

# builds a directory structure of a CLI to be released
# this is the starting point for any build
# It includes:
#
# * node binary
# * node modules
# * bin scripts

source ./scripts/main
source ./scripts/circle/vars

set -x

# setup workspace
rm -rf "${TARBALL_BASE_DIR}"
mkdir -p "${TARBALL_BASE_DIR}/node_modules"
mkdir -p "${TARBALL_BASE_DIR}/bin"
cp "${root}/README.md" "${TARBALL_BASE_DIR}"
cp "${root}/LICENSE" "${TARBALL_BASE_DIR}"
cp "${root}/package.json" "${TARBALL_BASE_DIR}"
cp "${root}/yarn.lock" "${TARBALL_BASE_DIR}"

bg "${root}/scripts/fetch_node_binary" "${TARBALL_BASE_DIR}/bin"

function install_packages {
  cd "${TARBALL_BASE_DIR}"
  # install packages
  yarn install --no-progress --production --non-interactive --prefer-offline --mutex=file:/tmp/.yarn-mutex

  # build cli-engine if needed
  if [ ! -f "${TARBALL_BASE_DIR}/node_modules/cli-engine/lib/cli.js" ]; then
    cd "${TARBALL_BASE_DIR}/node_modules/cli-engine"
    yarn
    yarn run prepare
  fi
}
bg install_packages

# create bin runner
if [ "${OS}" == "windows" ]; then
  cat << EOF > "${TARBALL_BASE_DIR}/bin/heroku.cmd"
@echo off
set CLI_BINPATH=%~dp0\\heroku.cmd
"%~dp0\\node.exe" "%~dp0\\heroku.js" %*
EOF
else
  cat << EOF > "${TARBALL_BASE_DIR}/bin/heroku"
#!/usr/bin/env bash
set -e
get_script_dir () {
  SOURCE="\${BASH_SOURCE[0]}"
  # While \$SOURCE is a symlink, resolve it
  while [ -h "\$SOURCE" ]; do
    DIR="\$( cd -P "\$( dirname "\$SOURCE" )" && pwd )"
    SOURCE="\$( readlink "\$SOURCE" )"
    # If \$SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
    [[ \$SOURCE != /* ]] && SOURCE="\$DIR/\$SOURCE"
  done
  DIR="\$( cd -P "\$( dirname "\$SOURCE" )" && pwd )"
  echo "\$DIR"
}
DIR=\$(get_script_dir)
# normalize home directory
CLI_HOME=\$(cd && pwd)
XDG_DATA_HOME=\${XDG_DATA_HOME:="\$CLI_HOME/.local/share"}
BIN_DIR="\$XDG_DATA_HOME/heroku/client/bin"
if [ -x "\$BIN_DIR/heroku" ] && [ ! "\$BIN_DIR" -ef "\$DIR" ]; then
  "\$XDG_DATA_HOME/heroku/client/bin/heroku" "\$@"
else
  CLI_BINPATH="\$DIR/heroku" "\$DIR/node" "\$DIR/heroku.js" "\$@"
fi
EOF
chmod +x "${TARBALL_BASE_DIR}/bin/heroku"
fi

cat << EOF > "${TARBALL_BASE_DIR}/bin/heroku.js"
const path = require('path')
const CLI = require('cli-engine').default
const root = path.join(__dirname, '..')
const cli = new CLI({
  argv: process.argv.slice(1),
  config: {
    root,
    pjson: require(path.join(root, 'package.json')),
    channel: '${CHANNEL}',
    version: '${VERSION}'
  }
})
cli.run()
EOF

wait_all
