#!/usr/bin/env bash

source ./scripts/main

set -x

output="$root/tmp/tarballs"

mkdir -p "${output}"

# create tarballs
tarball_base="${output}/$(base)"
cd "$root/tmp/builds"
bg tar c "$(base)" | xz > "${tarball_base}.tar.xz"
bg tar czf "${tarball_base}.tar.gz" "$(base)"
wait_all

sha256=$(shasum -a 256 "${tarball_base}.tar.gz" | awk \{'print $1'\})
sha256xz=$(shasum -a 256 "${tarball_base}.tar.xz" | awk \{'print $1'\})
cat << EOF > "${output}/${OS}-${ARCH}"
{
  "channel": "$(channel)",
  "version": "$(version)",
  "sha256gz": "${sha256}",
  "sha256xz": "${sha256xz}"
}
EOF
