#!/usr/bin/env bash

source ./scripts/main
source ./scripts/circle/vars

set -x

# create tarballs
cd "$BUILD_DIR"

# must be a directory in this format
# but it is difficult to work with the version number in other places
mv "$TARBALL_BASE_DIR" "$BUILD_DIR/$BASE" 

bg tar c "${BASE}" | xz > "$TXZ_PATH"
bg tar czf "$TGZ_PATH" "${BASE}"
wait_all

# move back into friendly format
mv "$BUILD_DIR/$BASE" "$TARBALL_BASE_DIR"

sha256=$(shasum -a 256 "$TGZ_PATH" | awk \{'print $1'\})
sha256xz=$(shasum -a 256 "$TXZ_PATH" | awk \{'print $1'\})
cat << EOF > "$BUILD_DIR/${OS}-${ARCH}"
{
  "channel": "${CHANNEL}",
  "version": "${VERSION}",
  "sha256gz": "${sha256}",
  "sha256xz": "${sha256xz}"
}
EOF
