#!/bin/bash

set -x

source ./scripts/main

if [ $# -ne 4 ]; then
  echo "USAGE: $0 OS ARCH CHANNEL OUTPUT_DIR"
  exit 1
fi

__os=$1
__arch=$2
__channel=$3
__output=$4

"${__root}/scripts/build_base" "${__os}" "${__arch}" "${__channel}" tmp/heroku

mkdir -p "${__output}"

# create tarballs
__tarball_base="${__output}/heroku-cli-${__os}-${__arch}"
tar c tmp/heroku | xz > "${__tarball_base}.tar.xz" &
tar czf "${__tarball_base}.tar.gz" tmp/heroku &
wait

__sha256=$(shasum -a 256 "${__tarball_base}.tar.gz" | awk \{'print $1'\})
__sha256xz=$(shasum -a 256 "${__tarball_base}.tar.xz" | awk \{'print $1'\})
cat << EOF > "${__os}-${__arch}"
{
  "channel": "${__channel}",
  "version": "${__version}",
  "sha256gz": "${__sha256}",
  "sha256xz": "${__sha256xz}"
}
EOF
