#!/bin/bash

if [ $# -ne 1 ]; then
  echo "USAGE: $0 ARCH"
  exit 1
fi

ARCH=$1

set -ex

ROOT=`pwd`

VERSION=`$ROOT/node_modules/cli-engine/bin/version`
DIST_DIR="dist/$VERSION"
INSTALLER_EXE="heroku-windows-$ARCH.exe"
INSTALLER="$DIST_DIR/$INSTALLER_EXE"
ARTIFACTS="$ROOT/tmp/artifacts"

if [ -e $INSTALLER ]; then
  mkdir -p $ARTIFACTS
  cp $INSTALLER $ARTIFACTS
fi
