#!/bin/bash

set -ex

ROOT=`pwd`

VERSION=`$ROOT/node_modules/cli-engine/bin/version`
NAME=`node -p "require('./package.json').name"`

# setup workspace
TARBALL_BASE=$NAME-v$VERSION-windows-$ARCH.tar.gz
WORKSPACE=$ROOT/tmp/build/$TARBALL_BASE

mkdir -p $ROOT/tmp/tarballs

ARCHS=(x86 x64)
for ARCH in "${ARCHS[@]}"; do
  if [ -e $WORKSPACE ]; then
    cp $WORKSPACE tmp/tarballs/windows-$ARCH.tar.gz
  fi
fi

find $ROOT/tmp/tarballs
