#!/usr/bin/env bash

source ./scripts/main

if [[ $# -ne 3 ]]; then
  echo "USAGE: $0 OS ARCH OUTPUT_DIR"
  exit 1
fi

os=$1
arch=$2
output=$3
node_ext=""

mkdir -p "${output}"
mkdir -p "${root}/tmp/node"
mkdir -p "${root}/tmp/cache/node"

# install node
if [ "${os}" == "windows" ]; then
  node_ext=".exe"
  node_base=node-v$(node_version)-win-${arch}
  if [ ! -f "${root}/tmp/cache/node/${node_base}" ]; then
    url=https://nodejs.org/dist/v$(node_version)/node-v$(node_version)-win-${arch}.7z
    curl -fSsLo "${root}/tmp/node/${node_base}.7z" "${url}"
    cd "${root}/tmp/node"
    7z x -bd -y "${root}/tmp/node/${node_base}.7z" > /dev/null
    mv "${node_base}/node.exe" "${root}/tmp/cache/node/${node_base}"
  fi
else
  if [ "${arch}" == "arm" ]; then node_arch=armv7l; else node_arch="${arch}"; fi
  node_base=node-v$(node_version)-${os}-${node_arch}
  if [ ! -f "${root}/tmp/cache/node/${node_base}" ]; then
    url=https://nodejs.org/dist/v$(node_version)/${node_base}.tar.xz
    curl -fSL "${url}" | tar -C "${root}/tmp/node" -xJ
    mv "${root}/tmp/node/${node_base}/bin/node" "${root}/tmp/cache/node/${node_base}"
  fi
fi

cd "${root}"
cp "${root}/tmp/cache/node/${node_base}" "${output}/node${node_ext}"
