#!/usr/bin/env bash

source ./scripts/main
source ./scripts/circle/vars

if [[ $# -ne 1 ]]; then
  echo "USAGE: $0 OUTPUT_DIR"
  exit 1
fi

output=$1
node_ext=""

mkdir -p "${output}"
mkdir -p "${root}/tmp/node"
mkdir -p "${root}/tmp/cache/node"

# install node
if [ "${OS}" == "windows" ]; then
  node_ext=".exe"
  node_base=node-v${NODE_VERSION}-win-${ARCH}
  if [ ! -f "${root}/tmp/cache/node/${node_base}" ]; then
    url=https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-win-${ARCH}.7z
    curl -fSsLo "${root}/tmp/node/${node_base}.7z" "${url}"
    cd "${root}/tmp/node"
    7z x -bd -y "${root}/tmp/node/${node_base}.7z" > /dev/null
    mv "${node_base}/node.exe" "${root}/tmp/cache/node/${node_base}"
  fi
else
  if [ "${ARCH}" == "arm" ]; then node_arch=armv7l; else node_arch="${ARCH}"; fi
  node_base=node-v${NODE_VERSION}-${OS}-${node_arch}
  if [ ! -f "${root}/tmp/cache/node/${node_base}" ]; then
    url=https://nodejs.org/dist/v${NODE_VERSION}/${node_base}.tar.xz
    curl -fSsL "${url}" | tar -C "${root}/tmp/node" -xJ
    mv "${root}/tmp/node/${node_base}/bin/node" "${root}/tmp/cache/node/${node_base}"
  fi
fi

cd "${root}"
cp "${root}/tmp/cache/node/${node_base}" "${output}/node${node_ext}"
