#!/usr/bin/env bash

# shellcheck disable=SC2034

# fail wait when any children fails
set -m

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

# Set magic variables for current file & dir
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$(dirname "${dir}")" && pwd)"

function version () {
  go_home
  if [[ -z "${_version-}" ]]; then
    _version=$(node -p "require('./package.json').version")
  fi
  echo "${_version}"
}

function node_version () {
  go_home
  if [[ -z "${_node_version-}" ]]; then
    _node_version=$(node -p "require('./package.json')['cli-engine'].node || process.versions.node")
  fi
  echo "${_node_version}"
}

function go_home () {
  cd "${root}"
}
go_home

CHANNEL=$(./scripts/circle/channel)
