#!/usr/bin/env bash

set -ex

VERSION=$(node -p "require('./package.json').version")

git submodule sync
git submodule update --init
cd cli
git tag "v$VERSION"
git push --tags

if [ -x /usr/local/bin/brew ]; then
  sleep 5
  /usr/local/bin/brew bump-formula-pr "--url=https://registry.npmjs.org/heroku-cli/-/heroku-cli-$VERSION.tgz"
else
  echo "homebrew not installed. Skipping formula bump." >&2
fi
