#!/usr/bin/env bash

source ./scripts/_init

set -x

yarn install --pure-lockfile --non-interactive
#yarn check

# build only if it is a git checkout
if [ ! -d "${ROOT_DIR}/node_modules/cli-engine/lib" ]; then
  cd "${ROOT_DIR}/node_modules/cli-engine" && yarn && cd ~/cli
fi
