#!/usr/bin/env node

const glob = require('glob')
const path = require('path')
const execa = require('execa')

// polyfill AbortController
global.fetch = require('node-fetch');
require('abortcontroller-polyfill/dist/polyfill-patch-fetch');
require('abortcontroller-polyfill/dist/abortcontroller-polyfill-only')
const c = require('@heroku-cli/color')

const packages = glob.sync(
  path.join(__dirname, '..', 'packages/*/package.json')
)

async function main() {
  for (const packageJSON of packages) {
    const pjson = require(packageJSON)
    if (pjson.scripts && pjson.scripts["prepack"]) {
      try {
        await execa('yarn', ['prepack'], {
          cwd: path.dirname(packageJSON),
          stdio: 'inherit'
        })
      } catch(e) {
        process.exit(1)
        return
      }
    }
  }
}


main()
