#!/usr/bin/env node

const glob = require('glob')
const path = require('path')
const execa = require('execa')

// polyfill AbortController
global.fetch = require('node-fetch');
require('abortcontroller-polyfill/dist/polyfill-patch-fetch');
require('abortcontroller-polyfill/dist/abortcontroller-polyfill-only')

const packages = glob.sync(
  path.join(__dirname, '..', 'packages/*/package.json')
)

async function main() {
  for (const packageJSON of packages) {
    const pjson = require(packageJSON)
    if (pjson.scripts && pjson.scripts["prepack"]) {
      const {exitCode, message} = await execa('yarn', ['prepack'], {
        cwd: path.dirname(packageJSON),
        stdio: 'inherit'
      })
      if (exitCode !== 0) {
        throw new Error(message)
      }
    }
  }
}


main()
