#!/usr/bin/env bash

set -e -o pipefail

CURRENT_BRANCH=$MERGED_BRANCH
if [[ -z $CURRENT_BRANCH ]]; then
  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
fi

RELEASE_PREFIX="release-"

if [[ "${CURRENT_BRANCH}" != *"${RELEASE_PREFIX}"*  ]]; then
  echo "scripts/publish-npm-latest must be run on a branch with this pattern: ${RELEASE_PREFIX}*."
  exit 1
fi

PACKAGE_VERSION=`node -e "console.log(require('./lerna.json').version)"`
TAG_NAME="v${PACKAGE_VERSION}"
EXISTING_REMOTE_TAG=$(git ls-remote origin "refs/tags/${TAG_NAME}")

if [ -n "${EXISTING_REMOTE_TAG}" ]; then
  echo "The tag ${TAG_NAME} already exists on github.com"
  echo "This likely means this version has already been published."
  echo "Please examine the tag ${TAG_NAME} on github.com/heroku/cli to see the contents of the ${TAG_NAME} release"
  echo "You may need to run scripts/create-release-pr to create a new release before running this script"
  exit 1
fi

echo "Installing dependencies with yarn..."
yarn
echo "Done installing dependencies with yarn"

echo "publishing packages to npm..."
yarn lerna publish --yes from-package

git tag "${TAG_NAME}" -m "${TAG_NAME}"
git push origin "${TAG_NAME}"
