#!/bin/bash

set -ex

if [ $# -ne 1 ]; then
  echo "USAGE: $0 CHANNEL"
  exit 1
fi

PROJECT_ROOT=/root/cli
cd $PROJECT_ROOT

# set constants
VERSION=$(node -p "require('./package.json').version")
SHA=$(git rev-parse --short HEAD)
DEB_VERSION="$VERSION-1"
ROOT=$PROJECT_ROOT/tmp/apt
CHANNEL=$1

rm -rf $ROOT

ARCHS=(x86 x64)
for ARCH in "${ARCHS[@]}"; do
  # set constants
  if [ "$ARCH" == "x64" ]; then DEB_ARCH=amd64; else DEB_ARCH=i386; fi
  DEB_BASE=heroku_${DEB_VERSION}_$DEB_ARCH
  WORKSPACE="$ROOT/$DEB_BASE.apt"
  DEB_FILE="$ROOT/$DEB_BASE.deb"

  # prep workspace
  mkdir -p "$WORKSPACE/DEBIAN"
  mkdir -p "$WORKSPACE/usr/bin"
  mkdir -p "$WORKSPACE/usr/lib"

  # copy install to workspace
  cp -r "tmp/build/heroku-cli-v$VERSION-$SHA-linux-$ARCH" "$WORKSPACE/usr/lib/heroku"

  # add bin loader scripts
  cat << EOF > "$WORKSPACE/usr/lib/heroku/bin/heroku"
#!/usr/bin/env bash
set -e
get_script_dir () {
  SOURCE="\${BASH_SOURCE[0]}"
  # While \$SOURCE is a symlink, resolve it
  while [ -h "\$SOURCE" ]; do
    DIR="\$( cd -P "\$( dirname "\$SOURCE" )" && pwd )"
    SOURCE="\$( readlink "\$SOURCE" )"
    # If \$SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
    [[ \$SOURCE != /* ]] && SOURCE="\$DIR/\$SOURCE"
  done
  DIR="\$( cd -P "\$( dirname "\$SOURCE" )" && pwd )"
  echo "\$DIR"
}
DIR=\$(get_script_dir)
CLI_BINPATH=\$DIR/heroku \$DIR/node \$DIR/heroku.js "\$@"
EOF
  chmod +x "$WORKSPACE/usr/lib/heroku/bin/heroku"

  cat << EOF > "$WORKSPACE/usr/lib/heroku/bin/heroku.js"
const path = require('path')
const CLI = require('cli-engine').default
const root = path.join(__dirname, '..')
const cli = new CLI({
  argv: process.argv.slice(1),
  config: {
    root,
    pjson: require(path.join(root, 'package.json')),
    channel: '$CHANNEL',
    version: '$VERSION',
    updateDisabled: 'update the CLI with "sudo apt-get upgrade heroku"'
  }
})
cli.run()
EOF

  # add debian config
  sed -e "s/Architecture: ARCHITECTURE/Architecture: $DEB_ARCH/" resources/deb/control | \
  sed -e "s/Version: VERSION/Version: $DEB_VERSION/" \
  > "$WORKSPACE/DEBIAN/control"

  # symlink bin
  ln -s ../lib/heroku/bin/heroku "$WORKSPACE/usr/bin/heroku"

  # reset permissions
  chown -R root "$WORKSPACE"
  chgrp -R root "$WORKSPACE"

  # build deb package
  dpkg --build "$WORKSPACE" "$DEB_FILE"
  rm -rf "$WORKSPACE"

done

# create Package apt file
cd $ROOT
apt-ftparchive packages . > Packages
apt-ftparchive -a amd64 packages . > Packages_amd64
apt-ftparchive -a i386 packages . > Packages_i386
gzip -c Packages > Packages.gz
gzip -c Packages_amd64 > Packages_amd64.gz
gzip -c Packages_i386 > Packages_i386.gz
bzip2 -k Packages
bzip2 -k Packages_amd64
bzip2 -k Packages_i386
xz -k Packages
xz -k Packages_amd64
xz -k Packages_i386

# create Release apt file
cd $ROOT
apt-ftparchive -c $PROJECT_ROOT/resources/deb/apt-ftparchive.conf release . > Release
gpg --digest-algo SHA512 --clearsign -u 0F1B0520 -o InRelease Release
gpg --digest-algo SHA512 -abs -u 0F1B0520 -o Release.gpg Release

# ship to s3
S3_HOST=heroku-cli-assets
REMOTE_PATH=/branches/$CHANNEL/apt
REMOTE_ROOT=s3://${S3_HOST}${REMOTE_PATH}
aws s3 cp --cache-control max-age=86400 "$ROOT/heroku_${DEB_VERSION}_amd64.deb" "$REMOTE_ROOT/heroku_${DEB_VERSION}_amd64.deb"
aws s3 cp --cache-control max-age=86400 "$ROOT/heroku_${DEB_VERSION}_i386.deb" "$REMOTE_ROOT/heroku_${DEB_VERSION}_i386.deb"
aws s3 cp --content-type text/plain --cache-control max-age=3600 "$ROOT/Release" "$REMOTE_ROOT/Release"
aws s3 cp --content-type text/plain --cache-control max-age=3600 "$ROOT/Release" "$REMOTE_ROOT/dists/stable/Release"
aws s3 cp --content-type text/plain --cache-control max-age=3600 "$ROOT/InRelease" "$REMOTE_ROOT/InRelease"
aws s3 cp --content-type text/plain --cache-control max-age=3600 "$ROOT/InRelease" "$REMOTE_ROOT/dists/stable/InRelease"
aws s3 cp --content-type text/plain --cache-control max-age=3600 "$ROOT/Release.gpg" "$REMOTE_ROOT/Release.gpg"
aws s3 cp --content-type text/plain --cache-control max-age=3600 "$ROOT/Release.gpg" "$REMOTE_ROOT/dists/stable/Release.gpg"
aws s3 cp --content-type text/plain --cache-control max-age=3600 "$ROOT/Packages" "$REMOTE_ROOT/Packages"
aws s3 cp --content-type text/plain --cache-control max-age=3600 "$ROOT/Packages" "$REMOTE_ROOT/dists/stable/Packages"
aws s3 cp --content-type text/plain --cache-control max-age=3600 "$ROOT/Packages" "$REMOTE_ROOT/dists/stable/main/binary-all/Packages"
aws s3 cp --content-type text/plain --cache-control max-age=3600 "$ROOT/Packages_i386" "$REMOTE_ROOT/dists/stable/main/binary-i386/Packages"
aws s3 cp --content-type text/plain --cache-control max-age=3600 "$ROOT/Packages_amd64" "$REMOTE_ROOT/dists/stable/main/binary-amd64/Packages"
aws s3 cp --cache-control max-age=3600 "$ROOT/Packages.bz2" "$REMOTE_ROOT/Packages.bz2"
aws s3 cp --cache-control max-age=3600 "$ROOT/Packages.gz" "$REMOTE_ROOT/Packages.gz"
aws s3 cp --cache-control max-age=3600 "$ROOT/Packages.xz" "$REMOTE_ROOT/Packages.xz"
aws s3 cp --cache-control max-age=3600 "$ROOT/Packages.bz2" "$REMOTE_ROOT/dists/stable/main/binary-all/Packages.bz2"
aws s3 cp --cache-control max-age=3600 "$ROOT/Packages.gz" "$REMOTE_ROOT/dists/stable/main/binary-all/Packages.gz"
aws s3 cp --cache-control max-age=3600 "$ROOT/Packages.xz" "$REMOTE_ROOT/dists/stable/main/binary-all/Packages.xz"
aws s3 cp --cache-control max-age=3600 "$ROOT/Packages_i386.bz2" "$REMOTE_ROOT/dists/stable/main/binary-i386/Packages.bz2"
aws s3 cp --cache-control max-age=3600 "$ROOT/Packages_i386.gz" "$REMOTE_ROOT/dists/stable/main/binary-i386/Packages.gz"
aws s3 cp --cache-control max-age=3600 "$ROOT/Packages_i386.xz" "$REMOTE_ROOT/dists/stable/main/binary-i386/Packages.xz"
aws s3 cp --cache-control max-age=3600 "$ROOT/Packages_amd64.bz2" "$REMOTE_ROOT/dists/stable/main/binary-amd64/Packages.bz2"
aws s3 cp --cache-control max-age=3600 "$ROOT/Packages_amd64.gz" "$REMOTE_ROOT/dists/stable/main/binary-amd64/Packages.gz"
aws s3 cp --cache-control max-age=3600 "$ROOT/Packages_amd64.xz" "$REMOTE_ROOT/dists/stable/main/binary-amd64/Packages.xz"

# update install-ubuntu.sh if changed
curl -S https://heroku-cli-assets.s3.amazonaws.com/install-ubuntu.sh > "$PROJECT_ROOT/tmp/install-ubuntu.sh"
if ! cmp -s tmp/install-ubuntu.sh resources/deb/install-ubuntu.sh; then
  aws s3 cp --content-type text/plain --cache-control max-age=3600 "$PROJECT_ROOT/resources/deb/install-ubuntu.sh" "s3://$S3_HOST/install-ubuntu.sh"
  aws cloudfront create-invalidation --distribution-id EHF9FOCUJYVZ --paths "/install-ubuntu.sh"
fi

# invalidate CDN
aws cloudfront create-invalidation --distribution-id EHF9FOCUJYVZ --paths \
  "$REMOTE_PATH/heroku_${DEB_VERSION}_amd64.deb" \
  "$REMOTE_PATH/heroku_${DEB_VERSION}_i386.deb"  \
  "$REMOTE_PATH/Release"                         \
  "$REMOTE_PATH/InRelease"                       \
  "$REMOTE_PATH/Release.gpg"                     \
  "$REMOTE_PATH/Packages"                        \
  "$REMOTE_PATH/Packages.bz2"                    \
  "$REMOTE_PATH/Packages.gz"
