#!/usr/bin/env bash

set -x

source ./scripts/main

if [ $# -ne 1 ]; then
  echo "USAGE: $0 INPUT_DIR"
  echo "INPUT_DIR is the result of running ./scripts/build_tarballs"
  exit 1
fi

input_dir=$1

remote_base=s3://$S3_BUCKET/heroku-cli/channels/$CHANNEL

pids=""
function upload () {
  bg aws s3 cp --quiet "$@"
}
function uploadDayCache () {
  upload --cache-control max-age=86400 "$@"
}
function uploadHourCache () {
  upload --cache-control max-age=3600 "$@"
}
uploadDayCache "${input_dir}/heroku-cli-$(version)-$OS-$ARCH.tar.xz" "$remote_base/heroku-cli-v$(version)-$OS-$ARCH.tar.xz"
uploadHourCache "$remote_base/heroku-cli-v$(version)-$OS-$ARCH.tar.xz" "$remote_base/heroku-cli-$OS-$ARCH.tar.xz"
uploadDayCache "${input_dir}/heroku-cli-v$(version)-$OS-$ARCH.tar.gz" "$remote_base/heroku-cli-v$(version)-$OS-$ARCH.tar.gz"
uploadHourCache "$remote_base/heroku-cli-v$(version)-$OS-$ARCH.tar.gz" "$remote_base/heroku-cli-$OS-$ARCH.tar.gz"
uploadHourCache --content-type application/json "${input_dir}/$OS-$ARCH" "$remote_base/$OS-$ARCH"

# shellcheck disable=SC2086
wait_all $pids
