#!/bin/bash

if [[ ($# -lt 2) || ($# -gt 3) ]]; then
  echo "USAGE: $0 type arch [branch]"
  exit 1
fi

set -ex

TYPE=$1
ARCH=$2
BRANCH=$3

do_release () {
  # TODO: add other release types
  if [ "${TYPE}" == "deb" ]; then
    yarn run release $1
    ./scripts/release-deb $1
  fi
}

if [ "${BRANCH}" != "" ]; then
  do_release "${BRANCH}"
elif [ "${CIRCLE_BRANCH}" == "master" ]; then
  TAG=`git describe --exact-match HEAD || echo NOTAG`
  if [ "${TAG}" != "NOTAG" ]; then
    do_release "stable"
  fi
  do_release "beta"
elif [ "${CIRCLE_BRANCH}" == "dev" ]; then
  do_release "dev"
fi
