#!/usr/bin/env bash

set -x

source ./scripts/main
source ./scripts/circle/vars

s3uploadDayCache "${root}/tmp/tarballs/heroku-cli-v${VERSION}-$OS-$ARCH.tar.xz" "${REMOTE_BASE}/heroku-cli-v${VERSION}-$OS-$ARCH.tar.xz"
s3uploadDayCache "${root}/tmp/tarballs/heroku-cli-v${VERSION}-$OS-$ARCH.tar.gz" "${REMOTE_BASE}/heroku-cli-v${VERSION}-$OS-$ARCH.tar.gz"
s3uploadHourCache "${REMOTE_BASE}/heroku-cli-v${VERSION}-$OS-$ARCH.tar.xz" "${REMOTE_BASE}/heroku-cli-$OS-$ARCH.tar.xz"
s3uploadHourCache "${REMOTE_BASE}/heroku-cli-v${VERSION}-$OS-$ARCH.tar.gz" "${REMOTE_BASE}/heroku-cli-$OS-$ARCH.tar.gz"
s3uploadHourCache --content-type application/json "${root}/tmp/tarballs/$OS-$ARCH" "${REMOTE_BASE}/$OS-$ARCH"

# wait_all
