#!/bin/bash

set -e

USAGE="Usage: $0 type -a arch -b branch"

while getopts ":a:b:" opt; do
  case $opt in
    a)
      ARCH_ARG="${OPTARG}"
      ;;
    b)
      BRANCH_ARG="${OPTARG}"
      ;;
    \?)
      echo "$USAGE"
      exit 1
      ;;
    :)
      echo "$USAGE"
      exit 1
      ;;
  esac
done

shift `expr $OPTIND - 1`

if [ $# -ne 1 ]; then
  echo "$USAGE"
  exit 1
fi

set -ex

TYPE=$1
ARCH=$ARCH_ARG
BRANCH=$BRANCH_ARG

do_release () {
  # TODO: add other release types
  if [ "${TYPE}" == "deb" ]; then
    yarn run release $1
    ./scripts/release-deb $1
  fi
}

if [ "${BRANCH}" != "" ]; then
  do_release "${BRANCH}"
elif [ "${CIRCLE_BRANCH}" == "master" ]; then
  TAG=`git describe --exact-match HEAD || echo NOTAG`
  if [ "${TAG}" != "NOTAG" ]; then
    do_release "stable"
  fi
  do_release "beta"
elif [ "${CIRCLE_BRANCH}" == "dev" ]; then
  do_release "dev"
fi
