#!/bin/bash

set -e -o pipefail
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen

apt-get -y update
apt-get install -y --no-install-recommends \
    apt-utils \
    bzip2 \
    curl \
    git \
    ca-certificates \
    ssh \
    osslsigncode \
    python-dev \
    locales \
    apt-transport-https \
    nsis \
    p7zip-full \
    xz-utils \
    gnupg \
    python3-pip

locale-gen 

