#!/usr/bin/env bash

source ./scripts/main

set -x

"${root}/scripts/lint"

function heroku () {
  "${root}/bin/run" "$@"
}

# smoke tests
heroku version
heroku help
heroku auth:whoami
APP=$(heroku apps | head -n2 | tail -n1)
heroku apps:info -a "$APP"
heroku run -a "$APP" echo "it works!"
