#!/usr/bin/env bash

source ./scripts/_init

set -x

"${root}/scripts/lint"
npx jest
npx flow
npx eslint .
npx flow

function heroku () {
  "${root}/bin/run" "$@"
}

# smoke tests
heroku version
heroku help
heroku auth:whoami
APP=$(heroku apps | head -n2 | tail -n1 | awk '{split($0, a); print a[1]}')
heroku apps:info -a "$APP"
heroku run --exit-code -a "$APP" echo "it works!"
