exports.topics = [
  { name: 'apps', description: 'manage apps' },
  { name: 'buildpacks', description: 'manage the buildpacks for an app' },
  { name: 'config', description: 'manage app config vars' },
  { name: 'create', hidden: true },
  { name: 'dashboard', hidden: true },
  { name: 'destroy', hidden: true },
  { name: 'domains', description: 'manage the domains for an app' },
  { name: 'dyno', hidden: true },
  { name: 'drains', description: 'list all log drains' },
  { name: 'features', description: 'manage optional features' },
  { name: 'info', hidden: true },
  { name: 'kill', hidden: true },
  { name: 'labs', description: 'experimental features' },
  { name: 'maintenance', description: 'manage maintenance mode for an app' },
  { name: 'notifications', description: 'display notifications' },
  { name: 'open', hidden: true },
  { name: 'ps', description: 'manage dynos (dynos, workers)' },
  { name: 'regions', description: 'list available regions' },
  { name: 'releases', description: 'manage app releases' },
  { name: 'rename', hidden: true },
  { name: 'resize', hidden: true },
  { name: 'restart', hidden: true },
  { name: 'scale', hidden: true },
  { name: 'stack', hidden: true },
  { name: 'stop', hidden: true }
]

exports.commands = [
  require('./commands/apps'),
  require('./commands/apps/create').apps,
  require('./commands/apps/create').root,
  require('./commands/apps/destroy').apps,
  require('./commands/apps/destroy').delete,
  require('./commands/apps/destroy').root,
  require('./commands/apps/errors'),
  require('./commands/apps/favorites'),
  require('./commands/apps/favorites/add'),
  require('./commands/apps/favorites/remove'),
  require('./commands/apps/info').apps,
  require('./commands/apps/info').root,
  require('./commands/apps/open').open,
  require('./commands/apps/open').root,
  require('./commands/apps/rename').apps,
  require('./commands/apps/rename').root,
  require('./commands/apps/stacks').apps,
  require('./commands/apps/stacks').root,
  require('./commands/apps/stacks/set').apps,
  require('./commands/apps/stacks/set').root,
  require('./commands/buildpacks'),
  require('./commands/buildpacks/add.js'),
  require('./commands/buildpacks/clear.js'),
  require('./commands/buildpacks/remove.js'),
  require('./commands/buildpacks/set.js'),
  require('./commands/config'),
  require('./commands/config/get'),
  require('./commands/config/set').add,
  require('./commands/config/set').set,
  require('./commands/config/unset').remove,
  require('./commands/config/unset').unset,
  require('./commands/dashboard'),
  require('./commands/domains'),
  require('./commands/domains/add'),
  require('./commands/domains/clear'),
  require('./commands/domains/remove'),
  require('./commands/domains/wait'),
  require('./commands/drains'),
  require('./commands/drains/add'),
  require('./commands/drains/remove'),
  require('./commands/features'),
  require('./commands/features/disable'),
  require('./commands/features/enable'),
  require('./commands/features/info'),
  require('./commands/keys'),
  require('./commands/keys/add'),
  require('./commands/keys/clear'),
  require('./commands/keys/remove'),
  require('./commands/labs'),
  require('./commands/labs/disable'),
  require('./commands/labs/enable'),
  require('./commands/labs/info'),
  require('./commands/maintenance'),
  require('./commands/maintenance/off'),
  require('./commands/maintenance/on'),
  require('./commands/notifications'),
  require('./commands/ps'),
  require('./commands/ps/restart').dyno,
  require('./commands/ps/restart').ps,
  require('./commands/ps/restart').restart,
  require('./commands/ps/scale').dyno,
  require('./commands/ps/scale').ps,
  require('./commands/ps/scale').root,
  require('./commands/ps/stop').dyno,
  require('./commands/ps/stop').dynoKill,
  require('./commands/ps/stop').kill,
  require('./commands/ps/stop').ps,
  require('./commands/ps/stop').psKill,
  require('./commands/ps/stop').stop,
  require('./commands/ps/type').dynoResize,
  require('./commands/ps/type').dynoType,
  require('./commands/ps/type').psResize,
  require('./commands/ps/type').resize,
  require('./commands/ps/type').type,
  require('./commands/regions'),
  require('./commands/releases'),
  require('./commands/releases/info'),
  require('./commands/releases/rollback')
]
