#!/usr/bin/env bash

echoerr() { echo "$@" 1>&2; }

# check if any git references exist
if grep -q -e "@git://" yarn.lock; then
  echoerr "git reference found in yarn.lock:"
  grep -e "@git://" yarn.lock 1>&2
  echoerr "this causes problems when some users try to npm install -g heroku-cli"
  echoerr "host the module on @heroku/foo"
  exit 1
fi

# run shellcheck
if [ -x "$(command -v shellcheck)" ]; then
  find scripts -type f -print0 | xargs -0 shellcheck --external-sources
else
  echoerr "install shellcheck to lint the scripts"
fi
