#!/usr/bin/env bash

source ./scripts/_init

set -ex

./scripts/build/base

function heroku () {
  node "$TMP_DIR/base/bin/heroku.js" "$@"
}

# enter tmp directory
cd "$(mktemp -d)"

# run tests
heroku version
heroku help
heroku auth:whoami

# fetch an app to work with
APP=$(heroku apps | head -n2 | tail -n1 | awk '{split($0, a); print a[1]}')
heroku apps:info -a "$APP"
heroku run --exit-code -a "$APP" echo "it works!"
