#!/usr/bin/env bash

source ./scripts/_init

set -ex

(
  # prep npm build
  npm pack
  mkdir -p "$tmp"
  TARBALL_FILENAME="heroku-cli-$SHORT_VERSION.tgz"
  mv "$TARBALL_FILENAME" "$tmp/heroku-cli.tgz"
  rm -rf "$tmp/package"
  cd "$tmp"
  tar -C "$tmp" -xzf "$tmp/heroku-cli.tgz"
  cd "$tmp/package"
  yarn --production
)

function heroku () {
  "$tmp/package/bin/run" "$@"
}

# enter tmp directory
cd "$(mktemp -d)"

# run tests
heroku version
heroku help
heroku auth:whoami

# fetch an app to work with
APP=$(heroku apps | head -n2 | tail -n1 | awk '{split($0, a); print a[1]}')
heroku apps:info -a "$APP"
heroku run --exit-code -a "$APP" echo "it works!"
