#!/usr/bin/env bash

source ./scripts/_init

set -ex

(
  # prep npm build
  npm pack
  mkdir -p "$TMP_DIR"
  TARBALL_FILENAME="heroku-cli-$SHORT_VERSION.tgz"
  mv "$TARBALL_FILENAME" "$TMP_DIR/heroku-cli.tgz"
  rm -rf "$TMP_DIR/package"
  cd "$TMP_DIR"
  tar -C "$TMP_DIR" -xzf "$TMP_DIR/heroku-cli.tgz"
  cd "$TMP_DIR/package"
  yarn --production
)

function heroku () {
  "$TMP_DIR/package/bin/run" "$@"
}

# enter tmp directory
cd "$(mktemp -d)"

# run tests
heroku version
heroku help
heroku auth:whoami

# fetch an app to work with
APP=$(heroku apps | head -n2 | tail -n1 | awk '{split($0, a); print a[1]}')
heroku apps:info -a "$APP"
heroku run --exit-code -a "$APP" echo "it works!"
