
name: heroku
version: '6.12.16'
summary: Heroku CLI
description: Heroku CLI
grade: stable
confinement: classic

apps:
    heroku:
        command: bin/heroku

parts:
  hello-node-snap:
    plugin: nodejs
    node-engine: 7.10.0
    node-packages:
      - heroku-cli
