name: heroku
version: git
summary: Heroku CLI
description: Heroku CLI
grade: stable
confinement: classic

apps:
  heroku:
    command: bin/heroku

parts:
  heroku:
    plugin: nodejs
    node-engine: 8.7.0
    node-packages:
      - heroku-cli
