name: heroku
version: git
summary: Heroku CLI
description: Heroku CLI
grade: stable
confinement: classic

apps:
  heroku:
    command: bin/heroku

parts:
  heroku:
    source: .
    plugin: nodejs
    node-engine: 8.7.0
