name: heroku
version: git
summary: Heroku CLI
description: Heroku CLI
grade: stable
confinement: classic

apps:
  heroku:
    command: bin/run

parts:
  heroku:
    plugin: nil
    override-build: |
      set -ex

      # install yarn
      apt-get update
      apt-get install -y curl
      curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      apt-get update
      apt-get install -y nodejs yarn

      cd packages/cli
      yarn
      yarn pack --filename heroku.tar.gz
      mv heroku.tar.gz ../..
      cd ../..
      tar xvzf heroku.tar.gz
      rmdir ../install
      mv package ../install
      OS=linux ./scripts/fetch_node_binary ../install/bin
      cd ../install && yarn --prod
      cd ../install && bin/run -v
      sed -i 's/#!\/usr\/bin\/env node/#!\/snap\/heroku\/current\/bin\/node/' ../install/bin/run
      sed -i "s/^process\.env\.HEROKU_UPDATE_INSTRUCTIONS.*$/process.env.HEROKU_UPDATE_INSTRUCTIONS = 'update with: snap refresh heroku'/" ../install/bin/run
      mkdir -p snap/hooks
      cat << EOF > snap/hooks/configure
      #!/bin/sh
      set -e
      export PATH="$SNAP_DATA/bin:$PATH"
      heroku update
      EOF
      chmod +x snap/hooks/configure
