name: acceptance tests

on:
  push:
    branches:
      - 'main'
jobs:
  acceptance:
    runs-on: ubuntu-latest
    environment: AcceptanceTests
    env:
      RUN_ACCEPTANCE_TESTS: true
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn --frozen-lockfile --network-timeout 1000000
      - name: Build packages
        run: yarn lerna run prepack
      - run: ./bin/run whoami
      - run: yarn lerna run test:acceptance