name: Create CLI Release

on:
  workflow_call:
    inputs:
      isStableCandidate:
        type: boolean
        description: Is this a stable/prod candidate?
        required: true
        default: false

jobs:
  get-version-channel:
    runs-on: ubuntu-latest
    outputs:
      channel: ${{ steps.getVersion.outputs.channel }}
      version: ${{ steps.getVersion.outputs.version }}
      # final check to ensure package.json doesn't have a dist tag, ex: '-beta'
      isStableRelease: ${{ fromJSON(inputs.isStableCandidate) && !steps.getVersion.outputs.channel }}
    steps:
      - uses: actions/checkout@v6
      - id: getVersion
        uses: ./.github/actions/get-version-and-channel/
        with:
          path: './package.json'

  publish-npm:
    needs: [get-version-channel]
    # if NOT isStableCandidate confirm dist tag is in package.json version
    if: fromJSON(needs.get-version-channel.outputs.isStableRelease) || (!fromJSON(inputs.isStableCandidate) && !!needs.get-version-channel.outputs.channel)
    # pub-hk-ubuntu-22.04- due to IP allow list issues with public repos: https://salesforce.quip.com/bu6UA0KImOxJ
    runs-on: pub-hk-ubuntu-22.04-small
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: Update npm for trusted publishing
        run: npm install -g npm@latest
      - name: Publish to NPM
        run: |
          PACKAGE_VERSION=$(node -e "console.log(require('./package.json').version)")
          PACKAGE_NAME=$(node -e "console.log(require('./package.json').name)")

          if npm view $PACKAGE_NAME@$PACKAGE_VERSION version &>/dev/null; then
            echo "Version $PACKAGE_VERSION already published to npm, skipping"
            exit 0
          fi

          if ${{ fromJSON(needs.get-version-channel.outputs.isStableRelease) }}
          then
            npm publish
          else
            npm publish --tag ${{ needs.get-version-channel.outputs.channel || 'beta' }}
          fi
        shell: bash

  pack-upload:
    needs: [publish-npm]
    uses: ./.github/workflows/pack-upload.yml
    secrets: inherit

  promote:
    needs: [get-version-channel, pack-upload]
    if: needs.pack-upload.result == 'success'
    uses: ./.github/workflows/promote-release.yml
    with:
      version: ${{ needs.get-version-channel.outputs.version }}
      isStableRelease: ${{ fromJSON(needs.get-version-channel.outputs.isStableRelease) }}
      channel: ${{ needs.get-version-channel.outputs.channel }}
    secrets: inherit

  publish-docs:
    needs: [get-version-channel, promote]
    uses: ./.github/workflows/devcenter-doc-update.yml
    with:
      isStableRelease: ${{ fromJSON(inputs.isStableCandidate) }}
    secrets: inherit
