name: Pack and Upload Windows Installers

on:
  workflow_dispatch:
  workflow_call:

jobs:
  pack-and-upload-windows:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_EC2_METADATA_DISABLED: true
    steps:
      - uses: actions/checkout@v7
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@8f3d1ec8a696b3b9d9a6c3696b6c73033cab69e4
      - name: Install NSIS
        run: brew install nsis
      - name: npm install
        run: npm ci
      - name: pack windows installer
        run: npm run pack:win
      - name: upload windows installer
        run: npm run upload:win
