name: Pack and Upload Windows Installers

on:
  workflow_dispatch:
  workflow_call:

jobs:
  pack-and-upload-windows:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_EC2_METADATA_DISABLED: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@41775cf0c82ef066f1eb39cea1bd74697ca5b735
      - name: Install NSIS
        run: brew install nsis
      - name: npm install
        run: npm ci
      - name: pack windows installer
        run: npm run oclif pack win --defender-exclusion hidden --root="./packages/cli"
      - name: upload windows installer
        run: npm run oclif upload win --root="./packages/cli"