name: Pack and Upload Windows Installers

on:
  workflow_dispatch:
  workflow_call:

jobs:
  pack-and-upload-windows:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_EC2_METADATA_DISABLED: true
    steps:
      - uses: actions/checkout@v7
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@b35a29a0f83ee8b8ca07b219fc8db3d7bb88ab49
      - name: Install NSIS
        run: brew install nsis
      - name: npm install
        run: npm ci
      - name: pack windows installer
        run: npm run pack:win
      - name: upload windows installer
        run: npm run upload:win
