name: Publish release to Change Management

on:
  workflow_dispatch:
    inputs:
      isStableCandidate:
        type: boolean
        description: Is this a stable/prod candidate?
        required: true
        default: false
  workflow_call:
    inputs:
      isStableCandidate:
        type: boolean
        description: Is this a stable/prod candidate?
        required: true
        default: false

jobs:
  publishToChangeManagement:
    runs-on: ubuntu-latest
    if: ${{ fromJSON(inputs.isStableCandidate) }}
    environment: ChangeManagement
    steps:
      # checkout required to get github.sha
      - uses: actions/checkout@v5
      - env:
          ACTOR_EMAIL: ${{ secrets.TPS_API_RELEASE_ACTOR_EMAIL }}
          TPS_API_TOKEN: ${{ secrets.TPS_API_TOKEN_PARAM }}
        run: ./scripts/postrelease/tps_record_release cli ${{ github.sha }}
